# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

PYTHON_COMPAT=( python3_{12..13} )
DISTUTILS_USE_PEP517=setuptools
PYPI_NO_NORMALIZE=1
PYPI_PN="homeassistant"
inherit distutils-r1 pypi readme.gentoo-r1 systemd

MY_PN=homeassistant

if [[ ${PV} == *9999* ]]; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/home-assistant/core.git"
	EGIT_BRANCH="dev"
	S="${WORKDIR}/homeassistant-full-9999/"
else
	MY_PV=${PV/_beta/b}
	MY_P=${MY_PN}-${MY_PV}
	SRC_URI="$(pypi_sdist_url homeassistant)
	https://github.com/home-assistant/core/archive/${MY_PV}.tar.gz -> ${MY_P}.gh.tar.gz"
fi

DESCRIPTION="Open-source home automation platform running on Python."
HOMEPAGE="https://home-assistant.io/ https://git.edevau.net/onkelbeh/HomeAssistantRepository/"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="amd64 arm arm64 x86"
IUSE="bh1750 blinkt bme280 bme680 cli coronavirus deutsche-bahn dht http loopenergy mariadb mosquitto mysql smarthab socat somfy ssl systemd tesla wink  abode acaia accuweather acer-projector acmeda adax adguard ads advantage-air aemet aftership agent-dvr airgradient airly airnow airq airthings-ble airthings airtouch4 airtouch5 airvisual airvisual-pro airzone-cloud airzone alarmdecoder alpha-vantage amazon-polly amberelectric ambient-network ambient-station amcrest ampio analytics-insights android-ip-webcam androidtv androidtv-remote anel-pwrctrl anova anthemav anthropic aosmith apache-kafka apcupsd apple-tv apprise aprilaire aprs apsystems aquacell aqualogic aquostv aranet arcam-fmj arris-tg2492lg aruba arve aseko-pool-live assist-pipeline asuswrt atag aten-pe atome august aurora-abb-powerone aurora aussie-broadband autarco avea avion awair aws aws-s3 axis azure-data-explorer azure-devops azure-event-hub azure-service-bus azure-storage backup baf baidu balboa bang-olufsen bbox beewi-smartclim bitcoin bizkaibus blackbird blebox blink blockchain blue-current bluemaestro bluesound bluetooth bluetooth-tracker bmw-connected-drive bond bosch-alarm bosch-shc braviatv bring broadlink brother brottsplatskartan brunt bryant-evolution bsblan bt-home-hub-5 bthome bt-smarthub buienradar caldav cambridge-audio camera canary cast ccm15 chacon-dio channels cisco-ios cisco-mobility-express cisco-webex-teams clementine cloudflare cloud cmus co2signal coinbase color-extractor comelit comfoconnect command-line compensation concord232 control4 conversation cookidoo coolmaster cppm-tracker cpuspeed crownstone cups daikin danfoss-air datadog deako debugpy deconz decora decora-wifi delijn deluge denonavr devialet devolo-home-control devolo-home-network dexcom dhcp digital-ocean directv discogs discord discovergy dlib-face-detect dlib-face-identify dlink dlna-dmr dlna-dms dnsip dominos doods doorbird dormakaba-dkey dremel-3d-printer drop-connect dsmr duke-energy dunehd duotecno dwd-weather-warnings dweet dynalite eafm easyenergy ebox ebusd ecoal-boiler ecobee ecoforest econet ecovacs ecowitt eddystone-temperature edimax edl21 efergy egardia eheimdigital electrasmart electric-kiwi elevenlabs elgato eliqonline elkm1 elmax elvia elv emby emoncms emonitor emulated-kasa emulated-roku energenie-power-sockets energyzero enigma2 enocean enphase-envoy entur-public-transport environment-canada envisalink ephember epic-games-store epion epson eq3btsmart escea esphome etherscan eufylife-ble eufy everlights evil-genius-labs evohome ezviz faa-delays familyhub fastdotcom feedreader ffmpeg fibaro fido file fints fireservicerota firmata fitbit fivem fixer fjaraskupan fleetgo flexit-bacnet flick-electric flic flipr flo flume flux-led folder-watcher foobot forecast-solar forked-daapd fortios foscam freebox freedompro free-mobile fritzbox-callmonitor fritzbox fritz fronius frontend frontier-silicon fujitsu-fglair fully-kiosk futurenow fyta garages-amsterdam gardena-bluetooth gc100 gdacs generic geniushub geocaching geo-json-events geonetnz-quakes geonetnz-volcano geo-rss-events gios github gitlab-ci gitter glances go2rtc goalzero gogogate2 goodwe google-assistant-sdk google-cloud google-drive google-generative-ai-conversation google-mail google google-maps google-photos google-pubsub google-sheets google-tasks google-translate google-travel-time govee-ble govee-light-local gpsd gree greeneye-monitor greenwave growatt-server gstreamer gtfs guardian habitica hardware harman-kardon-avr harmony hassio hdmi-cec heatmiser heos here-travel-time hikvisioncam hikvision hisense-aehw4a1 hive hko hlk-sw16 holiday homeassistant-hardware home-connect homee homekit-controller homekit homematicip-cloud homematic homewizard homeworks honeywell horizon hp-ilo html5 huawei-lte hue huisbaasje hunterdouglas-powerview husqvarna-automower-ble husqvarna-automower huum hvv-departures hydrawise hyperion ialarm iammeter iaqualink ibeacon icloud idasen-desk idteck-prox ifttt iglo igloohome ign-sismologia ihc image-upload imap imeon-inverter imgw-pib improv-ble incomfort influxdb inkbird insteon intellifire intesishome iometer iotawatt iotty iperf3 ipma ipp iqvia irish-rail-transport iron-os isal iskra islamic-prayer-times israel-rail iss ista-ecotrend isy994 itach ituran izone jellyfin jewish-calendar joaoapps-join juicenet justnimbus jvc-projector kaiterra kaleidescape keba keenetic-ndms2 kef kegtron keyboard keyboard-remote keymitt-ble kira kiwi kmtronic knocki knx kodi konnected kostal-plenticore kraken kulersky kwb lacrosse lacrosse-view lamarzocco lametric landisgyr-heat-meter lastfm launch-library laundrify lcn ld2410-ble leaone led-ble lektrico letpot lg-netcast lg-soundbar lg-thinq lidarr lifx lightwave limitlessled linear-garage-door linkplay linode linux-battery lirc litejet litterrobot livisi local-calendar local-todo london-underground lookin loqed luci luftdaten lupusec lutron-caseta lutron lw12wifi lyric madvr mailgun marytts mastodon matrix matter maxcube mcp mcp-server mealie meater medcom-ble media-extractor mediaroom melcloud melissa melnor message-bird met-eireann meteoalarm meteoclimatic meteo-france met metoffice mfi microbees microsoft miele mikrotik mill minecraft-server minio moat mobile-app mochad modbus modem-callerid modern-forms moehlenhoff-alpha2 monarch-money monoprice monzo mopeka motionblinds-ble motion-blinds motioneye motionmount mpd mqtt msteams mullvad music-assistant mutesync mysensors mystrom mythicbeastsdns myuplink nad namecheapdns nam nanoleaf nasweb neato nederlandse-spoorwegen ness-alarm nest netatmo netdata netgear-lte netgear netio network neurio-energy nexia nextbus nextcloud nextdns nfandroidtv nibe-heatpump nice-go nightscout niko-home-control nilu nina nissan-leaf nmap-tracker nmbs noaa-tides nobo-hub nordpool norway-air notify-events notion nsw-fuel-station nsw-rural-fire-service-feed ntfy nuheat nuki numato nut nws nx584 nyt-games nzbget oasa-telematics obihai octoprint oem ohmconnect ohme ollama ombi omnilogic ondilo-ico onedrive onewire onkyo onvif openai-conversation openerz openevse openexchangerates opengarage openhome open-meteo opensensemap opensky opentherm-gw openuv openweathermap opnsense opower opple oralb oru orvibo osoenergy osramlightify otbr otp ourgroceries overkiz overseerr ovo-energy owntracks p1-monitor palazzetti panasonic-bluray panasonic-viera pandora peblar peco pegel-online pencom permobil pglab philips-js picnic pi-hole pilight ping pjlink plaato plex plugwise plum-lightpad pocketcasts point poolsense powerfox powerwall private-ble-device profiler progettihwsw proliphix prometheus prosegur proxmoxve proxy prusalink ps4 pterodactyl pulseaudio-loopback pure-energie purpleair pushbullet pushover pvoutput pvpc-hourly-pricing pyload python-script qbittorrent qbus qingping qld-bushfire qnap qnap-qsw qrcode quantum-gateway qvr-pro qwikswitch rabbitair rachio radarr radio-browser radiotherm rainbird raincloud rainforest-eagle rainforest-raven rainmachine rapt-ble raspyrfm rdw recollect-waste recorder recswitch reddit refoss rehlko rejseplanen remember-the-milk remote-calendar remote-rpi-gpio renault renson reolink repetier rest rflink rfxtrx ridwell ring ripple risco rituals-perfume-genie rmvtransport roborock rocketchat roku romy roomba roon route53 rova rpi-power ruckus-unleashed russound-rio russound-rnet +ruuvi-gateway ruuvitag-ble rympro sabnzbd saj samsungtv sanix satel-integra schlage schluter scrape screenlogic scsgate season sendgrid sense sensibo sensirion-ble sensorpro sensorpush-cloud sensorpush sensoterra sentry senz serial serial-pm sesame seven-segments seventeentrack sfr-box sharkiq +shelly shodan sia sighthound signal-messenger simplefin simplepush simplisafe sinch sisyphus skybeacon skybell sky-hub sky-remote slack sleepiq slide-local slide slimproto sma smappee smart-meter-texas smartthings smarttub smarty smhi smlight sms snapcast snmp snoo snooz solaredge-local solaredge solarlog solax soma somfy-mylink sonarr songpal sonos sony-projector soundtouch spc speedtestdotnet splunk spotify sql squeezebox srp-energy ssdp starline starlingbank starlink startca statsd steamist steam-online stiebel-eltron stookwijzer streamlabswater stream subaru suez-water supla surepetcare swiss-hydrological-data swiss-public-transport switchbee switchbot-cloud switchbot switcher-kis switchmate syncthing syncthru synology-dsm synology-srm system-bridge systemmonitor tado tailscale tailwind tami4 tankerkoenig tank-utility tapsaff tasmota tautulli technove ted5000 tedee telegram-bot tellduslive tellstick temper tensorflow tesla-fleet tesla-wall-connector teslemetry tessie thermobeacon thermopro thethingsnetwork thingspeak thinkingcleaner thread tibber tikteck tile tilt-ble tmb todoist tolo tomorrowio toon totalconnect touchline touchline-sl tplink-lte tplink tplink-omada traccar traccar-server tractive tradfri trafikverket-camera trafikverket-ferry trafikverket-train trafikverket-weatherstation transmission transport-nsw travisci trend triggercmd tts tuya twentemilieu twilio twinkly twitch twitter ubus ukraine-alarm unifi-direct unifiled unifi unifiprotect upb upc-connect upcloud upnp uptimerobot usb usgs-earthquakes-feed utility-meter uvc v2c vallox vasttrafik velbus velux venstar vera verisure versasense version vesync vicare vilfo vivotek vizio vlc vlc-telnet vodafone-station voip volkszaehler volumio volvooncall vulcan vultr w800rf32 wake-on-lan wallbox waqi waterfurnace watergate watson-iot watttime waze-travel-time weatherflow-cloud weatherflow weatherkit webdav webmin webostv weheat wemo whirlpool whois wiffi wilight wirelesstag withings wiz wled wmspro wolflink workday ws66i wyoming xbox xeoma xiaomi-aqara xiaomi-ble xiaomi-miio xiaomi-tv xmpp xs1 yale yale-smart-alarm yalexs-ble yamaha yamaha-musiccast yandex-transport yardian yeelight yeelightsunflower yi yolink youless youtube zabbix zamg zeroconf zerproc zestimate zeversolar zha zhong-hong ziggo-mediabox-xl zoneminder zwave-js zwave-me blinkt bme280 bme680 cli coronavirus deutsche-bahn dht http loopenergy mariadb mosquitto smarthab socat somfy tesla wink"
RESTRICT="!test? ( test )"

# external deps
RDEPEND="${PYTHON_DEPS} acct-group/${MY_PN} acct-user/${MY_PN}
	|| ( dev-lang/python:3.12 dev-lang/python:3.13 )
	app-admin/logrotate
	dev-db/sqlite
	dev-libs/libfastjson
	dev-libs/xerces-c"
REQUIRED_USE="bluetooth? ( ruuvi-gateway shelly )
	homekit-controller? ( bluetooth )"
# Home Assistant Core dependencies from /var/tmp/portage/app-misc/homeassistant-2025.5.2/work/core-2025.5.2/homeassistant/package_constraints.txt
RDEPEND="${RDEPEND}

	~dev-python/aiodhcpwatcher-1.1.1[${PYTHON_USEDEP}]
	~dev-python/aiodiscover-2.7.0[${PYTHON_USEDEP}]
	~dev-python/aiodns-3.4.0[${PYTHON_USEDEP}]
	~dev-python/aiohasupervisor-0.3.1[${PYTHON_USEDEP}]
	~dev-python/aiohttp-asyncmdnsresolver-0.1.1[${PYTHON_USEDEP}]
	~dev-python/aiohttp-fast-zlib-0.2.3[${PYTHON_USEDEP}]
	~dev-python/aiohttp-3.11.18[${PYTHON_USEDEP}]
	~dev-python/aiohttp-cors-0.7.0[${PYTHON_USEDEP}]
	~dev-python/aiousbwatcher-1.1.1[${PYTHON_USEDEP}]
	~dev-python/aiozoneinfo-0.2.3[${PYTHON_USEDEP}]
	~dev-python/annotatedyaml-0.4.5[${PYTHON_USEDEP}]
	~dev-python/astral-2.2[${PYTHON_USEDEP}]
	~dev-python/async-interrupt-1.2.2[${PYTHON_USEDEP}]
	~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}]
	~dev-python/atomicwrites-1.4.1[${PYTHON_USEDEP}]
	~dev-python/attrs-25.1.0[${PYTHON_USEDEP}]
	~dev-python/audioop-lts-0.2.1[${PYTHON_USEDEP}]
	~dev-python/av-13.1.0[${PYTHON_USEDEP}]
	~dev-python/awesomeversion-24.6.0[${PYTHON_USEDEP}]
	~dev-python/bcrypt-4.2.0[${PYTHON_USEDEP}]
	~dev-python/bleak-retry-connector-3.9.0[${PYTHON_USEDEP}]
	~dev-python/bleak-0.22.3[${PYTHON_USEDEP}]
	~dev-python/bluetooth-adapters-0.21.4[${PYTHON_USEDEP}]
	~dev-python/bluetooth-auto-recovery-1.5.1[${PYTHON_USEDEP}]
	~dev-python/bluetooth-data-tools-1.28.1[${PYTHON_USEDEP}]
	~dev-python/cached-ipaddress-0.10.0[${PYTHON_USEDEP}]
	>=dev-python/certifi-2021.5.30[${PYTHON_USEDEP}]
	~dev-python/ciso8601-2.3.2[${PYTHON_USEDEP}]
	~dev-python/cronsim-2.6[${PYTHON_USEDEP}]
	~dev-python/cryptography-44.0.1[${PYTHON_USEDEP}]
	~dev-python/dbus-fast-2.43.0[${PYTHON_USEDEP}]
	~dev-python/fnv-hash-fast-1.5.0[${PYTHON_USEDEP}]
	~dev-python/go2rtc-client-0.1.2[${PYTHON_USEDEP}]
	~dev-python/ha-ffmpeg-3.2.2[${PYTHON_USEDEP}]
	~dev-python/habluetooth-3.48.2[${PYTHON_USEDEP}]
	~dev-python/hass-nabucasa-0.96.0[${PYTHON_USEDEP}]
	~dev-python/hassil-2.2.3[${PYTHON_USEDEP}]
	~dev-python/home-assistant-bluetooth-1.13.1[${PYTHON_USEDEP}]
	~dev-python/home-assistant-frontend-20250516.0[${PYTHON_USEDEP}]
	~dev-python/home-assistant-intents-2025.5.7[${PYTHON_USEDEP}]
	~dev-python/httpx-0.28.1[${PYTHON_USEDEP}]
	~dev-python/ifaddr-0.2.0[${PYTHON_USEDEP}]
	~dev-python/jinja2-3.1.6[${PYTHON_USEDEP}]
	~dev-python/lru-dict-1.3.0[${PYTHON_USEDEP}]
	~media-libs/mutagen-1.47.0[${PYTHON_USEDEP}]
	~dev-python/numpy-2.2.2[${PYTHON_USEDEP}]
	~dev-python/orjson-3.10.18[${PYTHON_USEDEP}]
	>=dev-python/packaging-23.1[${PYTHON_USEDEP}]
	~dev-python/paho-mqtt-2.1.0[${PYTHON_USEDEP}]
	~dev-python/pillow-11.2.1[${PYTHON_USEDEP}]
	~dev-python/propcache-0.3.1[${PYTHON_USEDEP}]
	~dev-python/psutil-home-assistant-0.0.1[${PYTHON_USEDEP}]
	~dev-python/pyjwt-2.10.1[${PYTHON_USEDEP}]
	~dev-python/pymicro-vad-1.0.1[${PYTHON_USEDEP}]
	~dev-python/pynacl-1.5.0[${PYTHON_USEDEP}]
	~dev-python/pyopenssl-25.0.0[${PYTHON_USEDEP}]
	~dev-python/pyserial-3.5[${PYTHON_USEDEP}]
	~dev-python/pyspeex-noise-1.0.2[${PYTHON_USEDEP}]
	~dev-python/python-slugify-8.0.4[${PYTHON_USEDEP}]
	~dev-python/pyturbojpeg-1.7.5[${PYTHON_USEDEP}]
	~dev-python/pyyaml-6.0.2[${PYTHON_USEDEP}]
	~dev-python/requests-2.32.3[${PYTHON_USEDEP}]
	~dev-python/securetar-2025.2.1[${PYTHON_USEDEP}]
	~dev-python/sqlalchemy-2.0.40[${PYTHON_USEDEP}]
	~dev-python/standard-aifc-3.13.0[${PYTHON_USEDEP}]
	~dev-python/standard-telnetlib-3.13.0[${PYTHON_USEDEP}]
	>=dev-python/typing-extensions-4.13.0[${PYTHON_USEDEP}]
	~dev-python/ulid-transform-1.4.0[${PYTHON_USEDEP}]
	>=dev-python/urllib3-1.26.5[${PYTHON_USEDEP}]
	>=dev-python/uv-0.7.1

	~dev-python/voluptuous-openapi-0.1.0[${PYTHON_USEDEP}]
	~dev-python/voluptuous-serialize-2.6.0[${PYTHON_USEDEP}]
	~dev-python/voluptuous-0.15.2[${PYTHON_USEDEP}]
	~dev-python/webrtc-models-0.3.0[${PYTHON_USEDEP}]
	~dev-python/yarl-1.20.0[${PYTHON_USEDEP}]
	~dev-python/zeroconf-0.147.0[${PYTHON_USEDEP}]
	>=dev-python/pycryptodome-3.6.6[${PYTHON_USEDEP}]
	>=dev-python/httplib2-0.19.0[${PYTHON_USEDEP}]
	~dev-python/grpcio-1.71.0[${PYTHON_USEDEP}]
	~dev-python/grpcio-status-1.71.0[${PYTHON_USEDEP}]
	~dev-python/grpcio-reflection-1.71.0[${PYTHON_USEDEP}]
	>=dev-python/btlewrap-0.0.10[${PYTHON_USEDEP}]
	~dev-python/anyio-4.9.0[${PYTHON_USEDEP}]
	~dev-python/h11-0.14.0[${PYTHON_USEDEP}]
	~dev-python/httpcore-1.0.7[${PYTHON_USEDEP}]
	>=dev-python/hyperframe-5.2.0[${PYTHON_USEDEP}]
	~dev-python/numpy-2.2.2[${PYTHON_USEDEP}]
	~dev-python/pandas-2.2.3[${PYTHON_USEDEP}]
	>=dev-python/multidict-6.0.2[${PYTHON_USEDEP}]
	>=dev-python/backoff-2.0[${PYTHON_USEDEP}]
	~dev-python/pydantic-2.11.3[${PYTHON_USEDEP}]
	>=dev-python/mashumaro-3.13.1[${PYTHON_USEDEP}]
	>=dev-python/pyopenssl-24.0.0[${PYTHON_USEDEP}]
	~dev-python/protobuf-5.29.2[${PYTHON_USEDEP}]
	>=dev-python/faust-cchardet-2.1.18[${PYTHON_USEDEP}]
	>=dev-python/websockets-13.1[${PYTHON_USEDEP}]
	dev-python/poetry
	~dev-python/charset-normalizer-3.4.0[${PYTHON_USEDEP}]
	>=dev-python/dacite-1.7.0[${PYTHON_USEDEP}]
	>=dev-python/chacha20poly1305-reuseable-0.13.0[${PYTHON_USEDEP}]
	>=dev-python/pycountry-23.12.11[${PYTHON_USEDEP}]
	>=net-analyzer/scapy-2.6.1[${PYTHON_USEDEP}]
	>=dev-python/tuf-4.0.0[${PYTHON_USEDEP}]
	~dev-python/async-timeout-4.0.3[${PYTHON_USEDEP}]
	>=dev-python/aiofiles-24.1.0[${PYTHON_USEDEP}]
	>=dev-python/multidict-6.4.2[${PYTHON_USEDEP}]
	~dev-python/rpds-py-0.24.0[${PYTHON_USEDEP}]"

# unknown origin, still something to clean up here

RDEPEND="${RDEPEND}
	~dev-python/colorlog-6.8.2[${PYTHON_USEDEP}]
	~dev-python/pyotp-2.8.0[${PYTHON_USEDEP}]
	>=dev-python/pyqrcode-1.2.1[${PYTHON_USEDEP}]"

# Module requirements from useflags
RDEPEND="${RDEPEND}
	bh1750? ( dev-python/i2csense[${PYTHON_USEDEP}] )
	blinkt? ( ~dev-python/blinkt-0.1.0[${PYTHON_USEDEP}] )
	bme280? ( dev-python/i2csense[${PYTHON_USEDEP}] dev-python/bme280spi[${PYTHON_USEDEP}] )
	bme680? ( dev-python/bme680[${PYTHON_USEDEP}] )
	cli? ( app-misc/home-assistant-cli )
	coronavirus? ( dev-python/coronavirus[${PYTHON_USEDEP}] )
	deutsche-bahn? ( dev-python/schiene[${PYTHON_USEDEP}] )
	dht? ( ~dev-python/adafruit-circuitpython-dht-3.7.0[${PYTHON_USEDEP}] ~dev-python/rpi-gpio-0.7.1_alpha4[${PYTHON_USEDEP}] )
	http? ( ~dev-python/aiohttp-cors-0.7.0[${PYTHON_USEDEP}] ~dev-python/aiohttp-fast-url-dispatcher-0.3.0[${PYTHON_USEDEP}] ~dev-python/aiohttp-zlib-ng-0.3.1[${PYTHON_USEDEP}] )
	loopenergy? ( ~dev-python/pyloopenergy-0.2.1[${PYTHON_USEDEP}] )
	mariadb? ( dev-python/mysqlclient[${PYTHON_USEDEP}] )
	mosquitto? ( app-misc/mosquitto )
	mysql? ( dev-python/mysqlclient[${PYTHON_USEDEP}] )
	smarthab? ( ~dev-python/smarthab-0.21[${PYTHON_USEDEP}] )
	socat? ( net-misc/socat )
	somfy? ( ~dev-python/pymfy-0.11.0[${PYTHON_USEDEP}] )
	ssl? ( dev-libs/openssl app-crypt/certbot net-proxy/haproxy )
	tesla? ( ~dev-python/teslajsonpy-0.18.3[${PYTHON_USEDEP}] )
	wink? ( ~dev-python/pubnubsub-handler-1.0.9[${PYTHON_USEDEP}] ~dev-python/python-wink-1.10.5[${PYTHON_USEDEP}] )
	abode? ( ~dev-python/jaraco-abode-6.2.1[${PYTHON_USEDEP}] )
	acaia? ( ~dev-python/aioacaia-0.1.14[${PYTHON_USEDEP}] )
	accuweather? ( ~dev-python/accuweather-4.2.0[${PYTHON_USEDEP}] )
	acer-projector? ( ~dev-python/pyserial-3.5[${PYTHON_USEDEP}] )
	acmeda? ( ~dev-python/aiopulse-0.4.6[${PYTHON_USEDEP}] )
	adax? ( ~dev-python/adax-local-0.1.5[${PYTHON_USEDEP}] ~dev-python/adax-0.4.0[${PYTHON_USEDEP}] )
	adguard? ( ~dev-python/adguardhome-0.7.0[${PYTHON_USEDEP}] )
	ads? ( ~dev-python/pyads-3.4.0[${PYTHON_USEDEP}] )
	advantage-air? ( ~dev-python/advantage-air-0.4.4[${PYTHON_USEDEP}] )
	aemet? ( ~dev-python/aemet-opendata-0.6.4[${PYTHON_USEDEP}] )
	aftership? ( ~dev-python/pyaftership-21.11.0[${PYTHON_USEDEP}] )
	agent-dvr? ( ~dev-python/agent-py-0.0.24[${PYTHON_USEDEP}] )
	airgradient? ( ~dev-python/airgradient-0.9.2[${PYTHON_USEDEP}] )
	airly? ( ~dev-python/airly-1.1.0[${PYTHON_USEDEP}] )
	airnow? ( ~dev-python/pyairnow-1.2.1[${PYTHON_USEDEP}] )
	airq? ( ~dev-python/aioairq-0.4.4[${PYTHON_USEDEP}] )
	airthings-ble? ( ~dev-python/airthings-ble-0.9.2[${PYTHON_USEDEP}] )
	airthings? ( ~dev-python/airthings-cloud-0.2.0[${PYTHON_USEDEP}] )
	airtouch4? ( ~dev-python/airtouch4pyapi-1.0.5[${PYTHON_USEDEP}] )
	airtouch5? ( ~dev-python/airtouch5py-0.2.11[${PYTHON_USEDEP}] )
	airvisual? ( ~dev-python/pyairvisual-2023.8.1[${PYTHON_USEDEP}] )
	airvisual-pro? ( ~dev-python/pyairvisual-2023.8.1[${PYTHON_USEDEP}] )
	airzone-cloud? ( ~dev-python/aioairzone-cloud-0.6.12[${PYTHON_USEDEP}] )
	airzone? ( ~dev-python/aioairzone-1.0.0[${PYTHON_USEDEP}] )
	alarmdecoder? ( ~dev-python/adext-0.4.4[${PYTHON_USEDEP}] )
	alpha-vantage? ( ~dev-python/alpha-vantage-2.3.1[${PYTHON_USEDEP}] )
	amazon-polly? ( ~dev-python/boto3-1.37.1[${PYTHON_USEDEP}] )
	amberelectric? ( ~dev-python/amberelectric-2.0.12[${PYTHON_USEDEP}] )
	ambient-network? ( ~dev-python/aioambient-2024.8.0[${PYTHON_USEDEP}] )
	ambient-station? ( ~dev-python/aioambient-2024.8.0[${PYTHON_USEDEP}] )
	amcrest? ( ~dev-python/amcrest-1.9.8[${PYTHON_USEDEP}] )
	ampio? ( ~dev-python/asmog-0.0.6[${PYTHON_USEDEP}] )
	analytics-insights? ( ~dev-python/python-homeassistant-analytics-0.9.0[${PYTHON_USEDEP}] )
	android-ip-webcam? ( ~dev-python/pydroid-ipcam-3.0.0[${PYTHON_USEDEP}] )
	androidtv? ( ~dev-python/adb-shell-0.4.4[async,${PYTHON_USEDEP}] ~dev-python/androidtv-0.0.75[async,${PYTHON_USEDEP}] )
	androidtv-remote? ( ~dev-python/androidtvremote2-0.2.1[${PYTHON_USEDEP}] )
	anel-pwrctrl? ( ~dev-python/anel-pwrctrl-homeassistant-0.0.1[${PYTHON_USEDEP}] )
	anova? ( ~dev-python/anova-wifi-0.17.0[${PYTHON_USEDEP}] )
	anthemav? ( ~dev-python/anthemav-1.4.1[${PYTHON_USEDEP}] )
	anthropic? ( ~dev-python/anthropic-0.47.2[${PYTHON_USEDEP}] )
	aosmith? ( ~dev-python/py-aosmith-1.0.12[${PYTHON_USEDEP}] )
	apache-kafka? ( ~dev-python/aiokafka-0.10.0[${PYTHON_USEDEP}] )
	apcupsd? ( ~dev-python/aioapcaccess-0.4.2[${PYTHON_USEDEP}] )
	apple-tv? ( ~dev-python/pyatv-0.16.0[${PYTHON_USEDEP}] )
	apprise? ( ~dev-python/apprise-1.9.1[${PYTHON_USEDEP}] )
	aprilaire? ( ~dev-python/pyaprilaire-0.8.1[${PYTHON_USEDEP}] )
	aprs? ( ~dev-python/aprslib-0.7.2[${PYTHON_USEDEP}] ~sci-geosciences/geopy-2.3.0[${PYTHON_USEDEP}] )
	apsystems? ( ~dev-python/apsystems-ez1-2.6.0[${PYTHON_USEDEP}] )
	aquacell? ( ~dev-python/aioaquacell-0.2.0[${PYTHON_USEDEP}] )
	aqualogic? ( ~dev-python/aqualogic-2.6[${PYTHON_USEDEP}] )
	aquostv? ( ~dev-python/sharp-aquos-rc-0.3.2[${PYTHON_USEDEP}] )
	aranet? ( ~dev-python/aranet4-2.5.1[${PYTHON_USEDEP}] )
	arcam-fmj? ( ~dev-python/arcam-fmj-1.8.1[${PYTHON_USEDEP}] )
	arris-tg2492lg? ( ~dev-python/arris-tg2492lg-2.2.0[${PYTHON_USEDEP}] )
	aruba? ( ~dev-python/pexpect-4.9.0[${PYTHON_USEDEP}] )
	arve? ( ~dev-python/asyncarve-0.1.1[${PYTHON_USEDEP}] )
	aseko-pool-live? ( ~dev-python/aioaseko-1.0.0[${PYTHON_USEDEP}] )
	assist-pipeline? ( ~dev-python/pymicro-vad-1.0.1[${PYTHON_USEDEP}] ~dev-python/pyspeex-noise-1.0.2[${PYTHON_USEDEP}] )
	asuswrt? ( ~dev-python/aioasuswrt-1.4.0[${PYTHON_USEDEP}] ~dev-python/pyasuswrt-0.1.21[${PYTHON_USEDEP}] )
	atag? ( ~dev-python/pyatag-0.3.5.3[${PYTHON_USEDEP}] )
	aten-pe? ( ~dev-python/auroranoaa-0.0.5[${PYTHON_USEDEP}] )
	atome? ( ~dev-python/pyatome-0.1.1[${PYTHON_USEDEP}] )
	august? ( ~dev-python/yalexs-ble-2.6.0[${PYTHON_USEDEP}] ~dev-python/yalexs-8.10.0[${PYTHON_USEDEP}] )
	aurora-abb-powerone? ( ~dev-python/aurorapy-0.2.7[${PYTHON_USEDEP}] )
	aurora? ( ~dev-python/auroranoaa-0.0.5[${PYTHON_USEDEP}] )
	aussie-broadband? ( ~dev-python/pyaussiebb-0.1.5[${PYTHON_USEDEP}] )
	autarco? ( ~dev-python/autarco-3.1.0[${PYTHON_USEDEP}] )
	avea? ( ~dev-python/axis-64[${PYTHON_USEDEP}] )
	avion? ( ~dev-python/axis-64[${PYTHON_USEDEP}] )
	awair? ( ~dev-python/python-awair-0.2.4[${PYTHON_USEDEP}] )
	aws? ( ~dev-python/aiobotocore-2.21.1[${PYTHON_USEDEP}] ~dev-python/botocore-1.37.1[${PYTHON_USEDEP}] )
	aws-s3? ( ~dev-python/aiobotocore-2.21.1[${PYTHON_USEDEP}] )
	axis? ( ~dev-python/axis-64[${PYTHON_USEDEP}] )
	azure-data-explorer? ( ~dev-python/azure-kusto-data-4.5.1[aio,${PYTHON_USEDEP}] ~dev-python/azure-kusto-ingest-4.5.1[${PYTHON_USEDEP}] )
	azure-devops? ( ~dev-python/aioazuredevops-2.2.1[${PYTHON_USEDEP}] )
	azure-event-hub? ( ~dev-python/azure-eventhub-5.11.1[${PYTHON_USEDEP}] )
	azure-service-bus? ( ~dev-python/azure-servicebus-7.10.0[${PYTHON_USEDEP}] )
	azure-storage? ( ~dev-python/azure-storage-blob-12.24.0[${PYTHON_USEDEP}] )
	backup? ( ~dev-python/cronsim-2.6[${PYTHON_USEDEP}] ~dev-python/securetar-2025.2.1[${PYTHON_USEDEP}] )
	baf? ( ~dev-python/aiobafi6-0.9.0[${PYTHON_USEDEP}] )
	baidu? ( ~dev-python/baidu-aip-1.6.6.0[${PYTHON_USEDEP}] )
	balboa? ( ~dev-python/pybalboa-1.1.3[${PYTHON_USEDEP}] )
	bang-olufsen? ( ~dev-python/mozart-api-4.1.1.116.4[${PYTHON_USEDEP}] )
	bbox? ( ~dev-python/pybbox-0.0.5_alpha0[${PYTHON_USEDEP}] )
	beewi-smartclim? ( ~dev-python/bimmer-connected-0.17.2[china,${PYTHON_USEDEP}] )
	bitcoin? ( ~dev-python/blockchain-1.4.4[${PYTHON_USEDEP}] )
	bizkaibus? ( ~dev-python/bizkaibus-0.1.1[${PYTHON_USEDEP}] )
	blackbird? ( ~dev-python/pyblackbird-0.6[${PYTHON_USEDEP}] )
	blebox? ( ~dev-python/blebox-uniapi-2.5.0[${PYTHON_USEDEP}] )
	blink? ( ~dev-python/blinkpy-0.23.0[${PYTHON_USEDEP}] )
	blockchain? ( ~dev-python/python-blockchain-api-0.0.2[${PYTHON_USEDEP}] )
	blue-current? ( ~dev-python/bluecurrent-api-1.2.3[${PYTHON_USEDEP}] )
	bluemaestro? ( ~dev-python/bluemaestro-ble-0.4.1[${PYTHON_USEDEP}] )
	bluesound? ( ~dev-python/pyblu-2.0.1[${PYTHON_USEDEP}] )
	bluetooth? ( ~dev-python/bleak-retry-connector-3.9.0[${PYTHON_USEDEP}] ~dev-python/bleak-0.22.3[${PYTHON_USEDEP}] ~dev-python/bluetooth-adapters-0.21.4[${PYTHON_USEDEP}] ~dev-python/bluetooth-auto-recovery-1.5.1[${PYTHON_USEDEP}] ~dev-python/bluetooth-data-tools-1.28.1[${PYTHON_USEDEP}] ~dev-python/dbus-fast-2.43.0[${PYTHON_USEDEP}] ~dev-python/habluetooth-3.48.2[${PYTHON_USEDEP}] )
	bluetooth-tracker? ( ~dev-python/pychromecast-14.0.7[${PYTHON_USEDEP}] ~dev-python/bt-proximity-0.2.1[${PYTHON_USEDEP}] )
	bmw-connected-drive? ( ~dev-python/bimmer-connected-0.17.2[china,${PYTHON_USEDEP}] )
	bond? ( ~dev-python/bond-async-0.2.1[${PYTHON_USEDEP}] )
	bosch-alarm? ( ~dev-python/bosch-alarm-mode2-0.4.6[${PYTHON_USEDEP}] )
	bosch-shc? ( ~dev-python/boschshcpy-0.2.91[${PYTHON_USEDEP}] )
	braviatv? ( ~dev-python/pybravia-0.3.4[${PYTHON_USEDEP}] )
	bring? ( ~dev-python/bring-api-1.1.0[${PYTHON_USEDEP}] )
	broadlink? ( ~dev-python/broadlink-0.19.0[${PYTHON_USEDEP}] )
	brother? ( ~dev-python/brother-4.3.1[${PYTHON_USEDEP}] )
	brottsplatskartan? ( ~dev-python/brottsplatskartan-1.0.5[${PYTHON_USEDEP}] )
	brunt? ( ~dev-python/brunt-1.2.0[${PYTHON_USEDEP}] )
	bryant-evolution? ( ~dev-python/evolutionhttp-0.0.18[${PYTHON_USEDEP}] )
	bsblan? ( ~dev-python/python-bsblan-1.2.1[${PYTHON_USEDEP}] )
	bt-home-hub-5? ( ~dev-python/bthomehub5-devicelist-0.1.1[${PYTHON_USEDEP}] )
	bthome? ( ~dev-python/bthome-ble-3.12.4[${PYTHON_USEDEP}] )
	bt-smarthub? ( ~dev-python/btsmarthub-devicelist-0.2.3[${PYTHON_USEDEP}] )
	buienradar? ( ~dev-python/buienradar-1.0.6[${PYTHON_USEDEP}] )
	caldav? ( ~dev-python/caldav-1.3.9[${PYTHON_USEDEP}] ~dev-python/icalendar-6.1.0[${PYTHON_USEDEP}] )
	cambridge-audio? ( ~dev-python/aiostreammagic-2.11.0[${PYTHON_USEDEP}] )
	camera? ( ~dev-python/pyturbojpeg-1.7.5[${PYTHON_USEDEP}] )
	canary? ( ~dev-python/py-canary-0.5.4[${PYTHON_USEDEP}] )
	cast? ( ~dev-python/pychromecast-14.0.7[${PYTHON_USEDEP}] )
	ccm15? ( ~dev-python/py-ccm15-0.0.9[${PYTHON_USEDEP}] )
	chacon-dio? ( ~dev-python/dio-chacon-wifi-api-1.2.2[${PYTHON_USEDEP}] )
	channels? ( ~dev-python/pychannels-1.2.3[${PYTHON_USEDEP}] )
	cisco-ios? ( ~dev-python/pexpect-4.9.0[${PYTHON_USEDEP}] )
	cisco-mobility-express? ( ~dev-python/ciscomobilityexpress-0.3.9[${PYTHON_USEDEP}] )
	cisco-webex-teams? ( ~dev-python/webexpythonsdk-2.0.1[${PYTHON_USEDEP}] )
	clementine? ( ~dev-python/python-clementine-remote-1.0.1[${PYTHON_USEDEP}] )
	cloudflare? ( ~dev-python/pycfdns-3.0.0[${PYTHON_USEDEP}] )
	cloud? ( ~dev-python/hass-nabucasa-0.96.0[${PYTHON_USEDEP}] )
	cmus? ( ~dev-python/pycmus-0.1.1[${PYTHON_USEDEP}] )
	co2signal? ( ~dev-python/aioelectricitymaps-0.4.0[${PYTHON_USEDEP}] )
	coinbase? ( ~dev-python/coinbase-advanced-py-1.2.2[${PYTHON_USEDEP}] ~dev-python/coinbase-2.1.0[${PYTHON_USEDEP}] )
	color-extractor? ( ~dev-python/colorthief-0.2.1[${PYTHON_USEDEP}] )
	comelit? ( ~dev-python/aiocomelit-0.12.1[${PYTHON_USEDEP}] )
	comfoconnect? ( ~dev-python/pycomfoconnect-0.5.1[${PYTHON_USEDEP}] )
	command-line? ( ~dev-python/jsonpath-0.82.2[${PYTHON_USEDEP}] )
	compensation? ( ~dev-python/numpy-2.2.2[${PYTHON_USEDEP}] )
	concord232? ( ~dev-python/concord232-0.15.1[${PYTHON_USEDEP}] )
	control4? ( ~dev-python/pycontrol4-1.2.0[${PYTHON_USEDEP}] )
	conversation? ( ~dev-python/hassil-2.2.3[${PYTHON_USEDEP}] ~dev-python/home-assistant-intents-2025.5.7[${PYTHON_USEDEP}] )
	cookidoo? ( ~dev-python/cookidoo-api-0.12.2[${PYTHON_USEDEP}] )
	coolmaster? ( ~dev-python/pycoolmasternet-async-0.2.2[${PYTHON_USEDEP}] )
	cppm-tracker? ( ~dev-python/clearpasspy-1.0.2[${PYTHON_USEDEP}] )
	cpuspeed? ( ~dev-python/py-cpuinfo-9.0.0[${PYTHON_USEDEP}] )
	crownstone? ( ~dev-python/crownstone-cloud-1.4.11[${PYTHON_USEDEP}] ~dev-python/crownstone-sse-2.0.5[${PYTHON_USEDEP}] ~dev-python/crownstone-uart-2.1.0[${PYTHON_USEDEP}] ~dev-python/pyserial-3.5[${PYTHON_USEDEP}] )
	cups? ( ~dev-python/pydaikin-2.15.0[${PYTHON_USEDEP}] )
	daikin? ( ~dev-python/pydaikin-2.15.0[${PYTHON_USEDEP}] )
	danfoss-air? ( ~dev-python/pydanfossair-0.1.0[${PYTHON_USEDEP}] )
	datadog? ( ~dev-python/datadog-0.15.0[${PYTHON_USEDEP}] )
	deako? ( ~dev-python/pydeako-0.6.0[${PYTHON_USEDEP}] )
	debugpy? ( ~dev-python/debugpy-1.8.13[${PYTHON_USEDEP}] )
	deconz? ( ~dev-python/pydeconz-120[${PYTHON_USEDEP}] )
	decora? ( ~dev-python/bluetooth-adapters-0.21.4[${PYTHON_USEDEP}] ~dev-python/deebot-client-13.2.0[${PYTHON_USEDEP}] )
	decora-wifi? ( ~dev-python/deebot-client-13.2.0[${PYTHON_USEDEP}] )
	delijn? ( ~dev-python/pydelijn-1.1.0[${PYTHON_USEDEP}] )
	deluge? ( ~dev-python/deluge-client-1.10.2[${PYTHON_USEDEP}] )
	denonavr? ( ~dev-python/denonavr-1.0.1[${PYTHON_USEDEP}] )
	devialet? ( ~dev-python/devialet-1.5.7[${PYTHON_USEDEP}] )
	devolo-home-control? ( ~dev-python/devolo-home-control-api-0.19.0[${PYTHON_USEDEP}] )
	devolo-home-network? ( ~dev-python/devolo-plc-api-1.5.1[${PYTHON_USEDEP}] )
	dexcom? ( ~dev-python/pydexcom-0.2.3[${PYTHON_USEDEP}] )
	dhcp? ( ~dev-python/aiodhcpwatcher-1.1.1[${PYTHON_USEDEP}] ~dev-python/aiodiscover-2.7.0[${PYTHON_USEDEP}] ~dev-python/cached-ipaddress-0.10.0[${PYTHON_USEDEP}] )
	digital-ocean? ( ~dev-python/python-digitalocean-1.13.2[${PYTHON_USEDEP}] )
	directv? ( ~dev-python/directv-0.4.0[${PYTHON_USEDEP}] )
	discogs? ( ~dev-python/discogs-client-2.3.0[${PYTHON_USEDEP}] )
	discord? ( ~dev-python/nextcord-2.6.0[${PYTHON_USEDEP}] )
	discovergy? ( ~dev-python/pydiscovergy-3.0.2[${PYTHON_USEDEP}] )
	dlib-face-detect? ( ~dev-python/fastdotcom-0.0.3[${PYTHON_USEDEP}] )
	dlib-face-identify? ( ~dev-python/fastdotcom-0.0.3[${PYTHON_USEDEP}] )
	dlink? ( ~dev-python/pyw215-0.7.0[${PYTHON_USEDEP}] )
	dlna-dmr? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] ~dev-python/getmac-0.9.5[${PYTHON_USEDEP}] )
	dlna-dms? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] )
	dnsip? ( ~dev-python/aiodns-3.4.0[${PYTHON_USEDEP}] )
	dominos? ( ~dev-python/pizzapi-0.0.6[${PYTHON_USEDEP}] )
	doods? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/pydoods-1.0.2[${PYTHON_USEDEP}] )
	doorbird? ( ~dev-python/doorbirdpy-3.0.8[${PYTHON_USEDEP}] )
	dormakaba-dkey? ( ~dev-python/py-dormakaba-dkey-1.0.5[${PYTHON_USEDEP}] )
	dremel-3d-printer? ( ~dev-python/dremel3dpy-2.1.1[${PYTHON_USEDEP}] )
	drop-connect? ( ~dev-python/dropmqttapi-1.0.3[${PYTHON_USEDEP}] )
	dsmr? ( ~dev-python/dsmr-parser-1.4.3[${PYTHON_USEDEP}] )
	duke-energy? ( ~dev-python/aiodukeenergy-0.3.0[${PYTHON_USEDEP}] )
	dunehd? ( ~dev-python/pdunehd-1.3.2[${PYTHON_USEDEP}] )
	duotecno? ( ~dev-python/pyduotecno-2024.10.1[${PYTHON_USEDEP}] )
	dwd-weather-warnings? ( ~dev-python/dwdwfsapi-1.0.7[${PYTHON_USEDEP}] )
	dweet? ( ~dev-python/dweepy-0.3.0[${PYTHON_USEDEP}] )
	dynalite? ( ~dev-python/dynalite-devices-0.1.47[${PYTHON_USEDEP}] ~dev-python/dynalite-panel-0.0.4[${PYTHON_USEDEP}] )
	eafm? ( ~dev-python/aioeafm-0.1.2[${PYTHON_USEDEP}] )
	easyenergy? ( ~dev-python/easyenergy-2.1.2[${PYTHON_USEDEP}] )
	ebox? ( ~dev-python/pyebox-1.1.4[${PYTHON_USEDEP}] )
	ebusd? ( ~dev-python/ebusdpy-0.0.17[${PYTHON_USEDEP}] )
	ecoal-boiler? ( ~dev-python/ecoaliface-0.4.0[${PYTHON_USEDEP}] )
	ecobee? ( ~dev-python/python-ecobee-api-0.2.20[${PYTHON_USEDEP}] )
	ecoforest? ( ~dev-python/pyecoforest-0.4.0[${PYTHON_USEDEP}] )
	econet? ( ~dev-python/pyeconet-0.1.28[${PYTHON_USEDEP}] )
	ecovacs? ( ~dev-python/deebot-client-13.2.0[${PYTHON_USEDEP}] ~dev-python/py-sucks-0.9.10[${PYTHON_USEDEP}] )
	ecowitt? ( ~dev-python/aioecowitt-2025.3.1[${PYTHON_USEDEP}] )
	eddystone-temperature? ( ~dev-python/beautifulsoup4-4.13.3[${PYTHON_USEDEP}] )
	edimax? ( ~dev-python/pyedimax-0.2.1[${PYTHON_USEDEP}] )
	edl21? ( ~dev-python/pysml-0.0.12[${PYTHON_USEDEP}] )
	efergy? ( ~dev-python/pyefergy-22.5.0[${PYTHON_USEDEP}] )
	egardia? ( ~dev-python/pythonegardia-1.0.52[${PYTHON_USEDEP}] )
	eheimdigital? ( ~dev-python/eheimdigital-1.1.0[${PYTHON_USEDEP}] )
	electrasmart? ( ~dev-python/pyelectra-1.2.4[${PYTHON_USEDEP}] )
	electric-kiwi? ( ~dev-python/electrickiwi-api-0.9.14[${PYTHON_USEDEP}] )
	elevenlabs? ( ~dev-python/elevenlabs-1.9.0[${PYTHON_USEDEP}] )
	elgato? ( ~dev-python/elgato-5.1.2[${PYTHON_USEDEP}] )
	eliqonline? ( ~dev-python/eliqonline-1.2.2[${PYTHON_USEDEP}] )
	elkm1? ( ~dev-python/elkm1-lib-2.2.11[${PYTHON_USEDEP}] )
	elmax? ( ~dev-python/elmax-api-0.0.6.4_rc0[${PYTHON_USEDEP}] )
	elvia? ( ~dev-python/elvia-0.1.0[${PYTHON_USEDEP}] )
	elv? ( ~dev-python/pypca-0.0.7[${PYTHON_USEDEP}] )
	emby? ( ~dev-python/pyemby-1.10[${PYTHON_USEDEP}] )
	emoncms? ( ~dev-python/pyemoncms-0.1.1[${PYTHON_USEDEP}] )
	emonitor? ( ~dev-python/aioemonitor-1.0.5[${PYTHON_USEDEP}] )
	emulated-kasa? ( ~dev-python/sense-energy-0.13.7[${PYTHON_USEDEP}] )
	emulated-roku? ( ~dev-python/emulated-roku-0.3.0[${PYTHON_USEDEP}] )
	energenie-power-sockets? ( ~dev-python/pyegps-0.2.5[${PYTHON_USEDEP}] )
	energyzero? ( ~dev-python/energyzero-2.1.1[${PYTHON_USEDEP}] )
	enigma2? ( ~dev-python/openwebifpy-4.3.1[${PYTHON_USEDEP}] )
	enocean? ( ~dev-python/enocean-0.50.1[${PYTHON_USEDEP}] )
	enphase-envoy? ( ~dev-python/pyenphase-1.26.1[${PYTHON_USEDEP}] )
	entur-public-transport? ( ~dev-python/enturclient-0.2.4[${PYTHON_USEDEP}] )
	environment-canada? ( ~dev-python/env-canada-0.10.2[${PYTHON_USEDEP}] )
	envisalink? ( ~dev-python/pyenvisalink-4.7[${PYTHON_USEDEP}] )
	ephember? ( ~dev-python/pyephember2-0.4.12[${PYTHON_USEDEP}] )
	epic-games-store? ( ~dev-python/epicstore-api-0.1.7[${PYTHON_USEDEP}] )
	epion? ( ~dev-python/epion-0.0.3[${PYTHON_USEDEP}] )
	epson? ( ~dev-python/epson-projector-0.5.1[${PYTHON_USEDEP}] )
	eq3btsmart? ( ~dev-python/bleak-esphome-2.15.1[${PYTHON_USEDEP}] ~dev-python/eq3btsmart-1.4.1[${PYTHON_USEDEP}] )
	escea? ( ~dev-python/pescea-1.0.12[${PYTHON_USEDEP}] )
	esphome? ( ~dev-python/aioesphomeapi-30.1.0[${PYTHON_USEDEP}] ~dev-python/bleak-esphome-2.15.1[${PYTHON_USEDEP}] ~dev-python/esphome-dashboard-api-1.3.0[${PYTHON_USEDEP}] )
	etherscan? ( ~dev-python/python-etherscan-api-0.0.3[${PYTHON_USEDEP}] )
	eufylife-ble? ( ~dev-python/eufylife-ble-client-0.1.8[${PYTHON_USEDEP}] )
	eufy? ( ~dev-python/lakeside-0.13[${PYTHON_USEDEP}] )
	everlights? ( ~dev-python/pyeverlights-0.1.0[${PYTHON_USEDEP}] )
	evil-genius-labs? ( ~dev-python/pyevilgenius-2.0.0[${PYTHON_USEDEP}] )
	evohome? ( ~dev-python/evohome-async-1.0.5[${PYTHON_USEDEP}] )
	ezviz? ( ~dev-python/pyezviz-0.2.1.2[${PYTHON_USEDEP}] )
	faa-delays? ( ~dev-python/faadelays-2023.9.1[${PYTHON_USEDEP}] )
	familyhub? ( ~dev-python/python-family-hub-local-0.0.2[${PYTHON_USEDEP}] )
	fastdotcom? ( ~dev-python/fastdotcom-0.0.3[${PYTHON_USEDEP}] )
	feedreader? ( ~dev-python/feedparser-6.0.11[${PYTHON_USEDEP}] )
	ffmpeg? ( ~dev-python/ha-ffmpeg-3.2.2[${PYTHON_USEDEP}] )
	fibaro? ( ~dev-python/pyfibaro-0.8.2[${PYTHON_USEDEP}] )
	fido? ( ~dev-python/pyfido-2.1.2[${PYTHON_USEDEP}] )
	file? ( ~dev-python/file-read-backwards-2.0.0[${PYTHON_USEDEP}] )
	fints? ( ~dev-python/fints-3.1.0[${PYTHON_USEDEP}] )
	fireservicerota? ( ~dev-python/pyfireservicerota-0.0.46[${PYTHON_USEDEP}] )
	firmata? ( ~dev-python/pymata-express-1.19[${PYTHON_USEDEP}] )
	fitbit? ( ~dev-python/fitbit-0.3.1[${PYTHON_USEDEP}] )
	fivem? ( ~dev-python/fivem-api-0.1.2[${PYTHON_USEDEP}] )
	fixer? ( ~dev-python/fixerio-1.0.0_alpha0[${PYTHON_USEDEP}] )
	fjaraskupan? ( ~dev-python/fjaraskupan-2.3.2[${PYTHON_USEDEP}] )
	fleetgo? ( ~dev-python/ritassist-0.9.2[${PYTHON_USEDEP}] )
	flexit-bacnet? ( ~dev-python/flexit-bacnet-2.2.3[${PYTHON_USEDEP}] )
	flick-electric? ( ~dev-python/pyflick-1.1.3[${PYTHON_USEDEP}] )
	flic? ( ~dev-python/pyflic-2.0.4[${PYTHON_USEDEP}] )
	flipr? ( ~dev-python/flipr-api-1.6.1[${PYTHON_USEDEP}] )
	flo? ( ~dev-python/aioflo-2021.11.0[${PYTHON_USEDEP}] )
	flume? ( ~dev-python/pyflume-0.6.5[${PYTHON_USEDEP}] )
	flux-led? ( ~dev-python/flux-led-1.2.0[${PYTHON_USEDEP}] )
	folder-watcher? ( ~dev-python/watchdog-6.0.0[${PYTHON_USEDEP}] )
	foobot? ( ~dev-python/foobot-async-1.0.0[${PYTHON_USEDEP}] )
	forecast-solar? ( ~dev-python/forecast-solar-4.2.0[${PYTHON_USEDEP}] )
	forked-daapd? ( ~dev-python/pyforked-daapd-0.1.14[${PYTHON_USEDEP}] ~dev-python/pylibrespot-java-0.1.1[${PYTHON_USEDEP}] )
	fortios? ( ~dev-python/fortiosapi-1.0.5[${PYTHON_USEDEP}] )
	foscam? ( ~dev-python/libpyfoscam-1.2.2[${PYTHON_USEDEP}] )
	freebox? ( ~dev-python/freebox-api-1.2.2[${PYTHON_USEDEP}] )
	freedompro? ( ~dev-python/pyfreedompro-1.1.0[${PYTHON_USEDEP}] )
	free-mobile? ( ~dev-python/freesms-0.2.0[${PYTHON_USEDEP}] )
	fritzbox-callmonitor? ( ~dev-python/fritzconnection-1.14.0[qrcode,${PYTHON_USEDEP}] )
	fritzbox? ( ~dev-python/pyfritzhome-0.6.17[${PYTHON_USEDEP}] )
	fritz? ( ~dev-python/fritzconnection-1.14.0[qrcode,${PYTHON_USEDEP}] >=dev-python/xmltodict-0.13.0[${PYTHON_USEDEP}] )
	fronius? ( ~dev-python/pyfronius-0.7.7[${PYTHON_USEDEP}] )
	frontend? ( ~dev-python/home-assistant-frontend-20250516.0[${PYTHON_USEDEP}] )
	frontier-silicon? ( ~dev-python/afsapi-0.2.7[${PYTHON_USEDEP}] )
	fujitsu-fglair? ( ~dev-python/ayla-iot-unofficial-1.4.7[${PYTHON_USEDEP}] )
	fully-kiosk? ( ~dev-python/python-fullykiosk-0.0.14[${PYTHON_USEDEP}] )
	futurenow? ( ~dev-python/pyfnip-0.2[${PYTHON_USEDEP}] )
	fyta? ( ~dev-python/fyta-cli-0.7.2[${PYTHON_USEDEP}] )
	garages-amsterdam? ( ~dev-python/odp-amsterdam-6.1.1[${PYTHON_USEDEP}] )
	gardena-bluetooth? ( ~dev-python/gardena-bluetooth-1.6.0[${PYTHON_USEDEP}] )
	gc100? ( ~dev-python/python-gc100-1.0.3_alpha0[${PYTHON_USEDEP}] )
	gdacs? ( ~dev-python/aio-georss-gdacs-0.10[${PYTHON_USEDEP}] )
	generic? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/av-13.1.0[${PYTHON_USEDEP}] )
	geniushub? ( ~dev-python/geniushub-client-0.7.1[${PYTHON_USEDEP}] )
	geocaching? ( ~dev-python/geocachingapi-0.3.0[${PYTHON_USEDEP}] )
	geo-json-events? ( ~dev-python/aio-geojson-generic-client-0.5[${PYTHON_USEDEP}] )
	geonetnz-quakes? ( ~dev-python/aio-geojson-geonetnz-quakes-0.16[${PYTHON_USEDEP}] )
	geonetnz-volcano? ( ~dev-python/aio-geojson-geonetnz-volcano-0.9[${PYTHON_USEDEP}] )
	geo-rss-events? ( ~dev-python/georss-generic-client-0.8[${PYTHON_USEDEP}] )
	gios? ( ~dev-python/gios-6.0.0[${PYTHON_USEDEP}] )
	github? ( ~dev-python/aiogithubapi-24.6.0[${PYTHON_USEDEP}] )
	gitlab-ci? ( ~dev-vcs/python-gitlab-1.6.0[${PYTHON_USEDEP}] )
	gitter? ( ~dev-python/gitterpy-0.1.7[${PYTHON_USEDEP}] )
	glances? ( ~dev-python/glances-api-0.8.0[${PYTHON_USEDEP}] )
	go2rtc? ( ~dev-python/go2rtc-client-0.1.2[${PYTHON_USEDEP}] )
	goalzero? ( ~dev-python/goalzero-0.2.2[${PYTHON_USEDEP}] )
	gogogate2? ( ~dev-python/ismartgate-5.0.2[${PYTHON_USEDEP}] )
	goodwe? ( ~dev-python/goodwe-0.3.6[${PYTHON_USEDEP}] )
	google-assistant-sdk? ( ~dev-python/gassist-text-0.0.12[${PYTHON_USEDEP}] )
	google-cloud? ( ~dev-python/google-cloud-speech-2.31.1[${PYTHON_USEDEP}] ~dev-python/google-cloud-texttospeech-2.25.1[${PYTHON_USEDEP}] )
	google-drive? ( ~dev-python/python-google-drive-api-0.1.0[${PYTHON_USEDEP}] )
	google-generative-ai-conversation? ( ~dev-python/google-genai-1.7.0[${PYTHON_USEDEP}] )
	google-mail? ( ~dev-python/google-api-python-client-2.71.0[${PYTHON_USEDEP}] )
	google? ( ~dev-python/gcal-sync-7.0.1[${PYTHON_USEDEP}] ~dev-python/ical-9.2.4[${PYTHON_USEDEP}] ~dev-python/oauth2client-4.1.3[${PYTHON_USEDEP}] )
	google-maps? ( ~dev-python/locationsharinglib-5.0.1[${PYTHON_USEDEP}] )
	google-photos? ( ~dev-python/google-photos-library-api-0.12.1[${PYTHON_USEDEP}] )
	google-pubsub? ( ~dev-python/google-cloud-pubsub-2.29.0[${PYTHON_USEDEP}] )
	google-sheets? ( ~dev-python/gspread-5.5.0[${PYTHON_USEDEP}] )
	google-tasks? ( ~dev-python/google-api-python-client-2.71.0[${PYTHON_USEDEP}] )
	google-translate? ( ~dev-python/gtts-2.5.3[${PYTHON_USEDEP}] )
	google-travel-time? ( ~dev-python/google-maps-routing-0.6.14[${PYTHON_USEDEP}] )
	govee-ble? ( ~dev-python/govee-ble-0.44.0[${PYTHON_USEDEP}] )
	govee-light-local? ( ~dev-python/govee-local-api-2.1.0[${PYTHON_USEDEP}] )
	gpsd? ( ~dev-python/gps3-0.33.3[${PYTHON_USEDEP}] )
	gree? ( ~dev-python/greeclimate-2.1.0[${PYTHON_USEDEP}] )
	greeneye-monitor? ( ~dev-python/greeneye-monitor-3.0.3[${PYTHON_USEDEP}] )
	greenwave? ( ~dev-python/greenwavereality-0.5.1[${PYTHON_USEDEP}] )
	growatt-server? ( ~dev-python/growattserver-1.6.0[${PYTHON_USEDEP}] )
	gstreamer? ( ~dev-python/gstreamer-player-1.1.2[${PYTHON_USEDEP}] )
	gtfs? ( ~dev-python/pygtfs-0.1.9[${PYTHON_USEDEP}] )
	guardian? ( ~dev-python/aioguardian-2022.7.0[${PYTHON_USEDEP}] )
	habitica? ( ~dev-python/habiticalib-0.3.7[${PYTHON_USEDEP}] )
	hardware? ( ~dev-python/psutil-home-assistant-0.0.1[${PYTHON_USEDEP}] )
	harman-kardon-avr? ( ~dev-python/hkavr-0.0.5[${PYTHON_USEDEP}] )
	harmony? ( ~dev-python/aioharmony-0.5.2[${PYTHON_USEDEP}] )
	hassio? ( ~dev-python/aiohasupervisor-0.3.1[${PYTHON_USEDEP}] )
	hdmi-cec? ( ~dev-python/pycec-0.5.2[${PYTHON_USEDEP}] )
	heatmiser? ( ~dev-python/heatmiserv3-2.0.3[${PYTHON_USEDEP}] )
	heos? ( ~dev-python/pyheos-1.0.5[${PYTHON_USEDEP}] )
	here-travel-time? ( ~dev-python/here-routing-1.0.1[${PYTHON_USEDEP}] ~dev-python/here-transit-1.2.1[${PYTHON_USEDEP}] )
	hikvisioncam? ( ~dev-python/hikvision-0.4[${PYTHON_USEDEP}] )
	hikvision? ( ~dev-python/pyhik-0.3.2[${PYTHON_USEDEP}] )
	hisense-aehw4a1? ( ~dev-python/pyaehw4a1-0.3.9[${PYTHON_USEDEP}] )
	hive? ( ~dev-python/pyhive-integration-1.0.2[${PYTHON_USEDEP}] )
	hko? ( ~dev-python/hko-0.3.2[${PYTHON_USEDEP}] )
	hlk-sw16? ( ~dev-python/hlk-sw16-0.0.9[${PYTHON_USEDEP}] )
	holiday? ( ~dev-python/babel-2.15.0[${PYTHON_USEDEP}] ~dev-python/holidays-0.72[${PYTHON_USEDEP}] )
	homeassistant-hardware? ( ~dev-python/ha-silabs-firmware-client-0.2.0[${PYTHON_USEDEP}] ~dev-python/universal-silabs-flasher-0.0.30[${PYTHON_USEDEP}] )
	home-connect? ( ~dev-python/aiohomeconnect-0.17.0[${PYTHON_USEDEP}] )
	homee? ( ~dev-python/pyhomee-1.2.8[${PYTHON_USEDEP}] )
	homekit-controller? ( ~dev-python/aiohomekit-3.2.14[${PYTHON_USEDEP}] )
	homekit? ( ~dev-python/hap-python-4.9.2[${PYTHON_USEDEP}] ~dev-python/pyqrcode-1.2.1[${PYTHON_USEDEP}] ~dev-python/base36-0.1.1[${PYTHON_USEDEP}] ~dev-python/fnv-hash-fast-1.5.0[${PYTHON_USEDEP}] )
	homematicip-cloud? ( ~dev-python/homematicip-2.0.1.1[${PYTHON_USEDEP}] )
	homematic? ( ~dev-python/pyhomematic-0.1.77[${PYTHON_USEDEP}] )
	homewizard? ( ~dev-python/python-homewizard-energy-8.3.2[${PYTHON_USEDEP}] )
	homeworks? ( ~dev-python/pyhomeworks-1.1.2[${PYTHON_USEDEP}] )
	honeywell? ( ~dev-python/aiosomecomfort-0.0.32[${PYTHON_USEDEP}] )
	horizon? ( ~dev-python/horimote-0.4.1[${PYTHON_USEDEP}] )
	hp-ilo? ( ~dev-python/python-hpilo-4.4.3[${PYTHON_USEDEP}] )
	html5? ( ~dev-python/pywebpush-1.14.1[${PYTHON_USEDEP}] )
	huawei-lte? ( ~dev-python/huawei-lte-api-1.11.0[${PYTHON_USEDEP}] ~dev-python/stringcase-1.2.0[${PYTHON_USEDEP}] ~dev-python/url-normalize-2.2.1[${PYTHON_USEDEP}] )
	hue? ( ~dev-python/aiohue-4.7.4[${PYTHON_USEDEP}] )
	huisbaasje? ( ~dev-python/energyflip-client-0.2.2[${PYTHON_USEDEP}] )
	hunterdouglas-powerview? ( ~dev-python/aiopvapi-3.1.1[${PYTHON_USEDEP}] )
	husqvarna-automower-ble? ( ~dev-python/automower-ble-0.2.0[${PYTHON_USEDEP}] )
	husqvarna-automower? ( ~dev-python/aioautomower-2025.5.1[${PYTHON_USEDEP}] )
	huum? ( ~dev-python/huum-0.7.12[${PYTHON_USEDEP}] )
	hvv-departures? ( ~dev-python/pygti-0.9.4[${PYTHON_USEDEP}] )
	hydrawise? ( ~dev-python/pydrawise-2025.3.0[${PYTHON_USEDEP}] )
	hyperion? ( ~dev-python/hyperion-py-0.7.5[${PYTHON_USEDEP}] )
	ialarm? ( ~dev-python/pyialarm-2.2.0[${PYTHON_USEDEP}] )
	iammeter? ( ~dev-python/iammeter-0.2.1[${PYTHON_USEDEP}] )
	iaqualink? ( ~dev-python/h2-4.2.0[${PYTHON_USEDEP}] ~dev-python/iaqualink-0.5.3[${PYTHON_USEDEP}] )
	ibeacon? ( ~dev-python/ibeacon-ble-1.2.0[${PYTHON_USEDEP}] )
	icloud? ( ~dev-python/pyicloud-1.0.0[${PYTHON_USEDEP}] )
	idasen-desk? ( ~dev-python/idasen-ha-2.6.3[${PYTHON_USEDEP}] )
	idteck-prox? ( ~dev-python/rfk101py-0.0.1[${PYTHON_USEDEP}] )
	ifttt? ( >=dev-python/pyfttt-0.3.0[${PYTHON_USEDEP}] )
	iglo? ( ~dev-python/iglo-1.2.7[${PYTHON_USEDEP}] )
	igloohome? ( ~dev-python/igloohome-api-0.1.0[${PYTHON_USEDEP}] )
	ign-sismologia? ( ~dev-python/georss-ign-sismologia-client-0.8[${PYTHON_USEDEP}] )
	ihc? ( =dev-python/defusedxml-0.7.1-r1[${PYTHON_USEDEP}] ~dev-python/ihcsdk-2.8.5[${PYTHON_USEDEP}] )
	image-upload? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] )
	imap? ( ~dev-python/aioimaplib-2.0.1[${PYTHON_USEDEP}] )
	imeon-inverter? ( ~dev-python/imeon-inverter-api-0.3.12[${PYTHON_USEDEP}] )
	imgw-pib? ( ~dev-python/imgw-pib-1.0.10[${PYTHON_USEDEP}] )
	improv-ble? ( ~dev-python/py-improv-ble-client-1.0.3[${PYTHON_USEDEP}] )
	incomfort? ( ~dev-python/incomfort-client-0.6.8[${PYTHON_USEDEP}] )
	influxdb? ( ~dev-python/influxdb-client-1.24.0[${PYTHON_USEDEP}] ~dev-python/influxdb-5.3.1[${PYTHON_USEDEP}] )
	inkbird? ( ~dev-python/inkbird-ble-0.16.1[${PYTHON_USEDEP}] )
	insteon? ( ~dev-python/insteon-frontend-home-assistant-0.5.0[${PYTHON_USEDEP}] ~dev-python/pyinsteon-1.6.3[${PYTHON_USEDEP}] )
	intellifire? ( ~dev-python/intellifire4py-4.1.9[${PYTHON_USEDEP}] )
	intesishome? ( ~dev-python/pyintesishome-1.8.0[${PYTHON_USEDEP}] )
	iometer? ( ~dev-python/iometer-0.1.0[${PYTHON_USEDEP}] )
	iotawatt? ( ~dev-python/ha-iotawattpy-0.1.2[${PYTHON_USEDEP}] )
	iotty? ( ~dev-python/iottycloud-0.3.0[${PYTHON_USEDEP}] )
	iperf3? ( ~dev-python/iperf3-0.1.11[${PYTHON_USEDEP}] )
	ipma? ( ~dev-python/pyipma-3.0.9[${PYTHON_USEDEP}] )
	ipp? ( ~dev-python/pyipp-0.17.0[${PYTHON_USEDEP}] )
	iqvia? ( ~dev-python/numpy-2.2.2[${PYTHON_USEDEP}] ~dev-python/pyiqvia-2022.4.0[${PYTHON_USEDEP}] )
	irish-rail-transport? ( ~dev-python/pyirishrail-0.0.2[${PYTHON_USEDEP}] )
	iron-os? ( ~dev-python/pynecil-4.1.0[${PYTHON_USEDEP}] )
	isal? ( ~dev-python/isal-1.7.1[${PYTHON_USEDEP}] )
	iskra? ( ~dev-python/pyiskra-0.1.15[${PYTHON_USEDEP}] )
	islamic-prayer-times? ( ~dev-python/prayer-times-calculator-offline-1.0.3[${PYTHON_USEDEP}] )
	israel-rail? ( ~dev-python/israel-rail-api-0.1.2[${PYTHON_USEDEP}] )
	iss? ( ~dev-python/pyiss-1.0.1[${PYTHON_USEDEP}] )
	ista-ecotrend? ( ~dev-python/pyecotrend-ista-3.3.1[${PYTHON_USEDEP}] )
	isy994? ( ~dev-python/pyisy-3.4.1[${PYTHON_USEDEP}] )
	itach? ( ~dev-python/pyitachip2ir-0.0.7[${PYTHON_USEDEP}] )
	ituran? ( ~dev-python/pyituran-0.1.4[${PYTHON_USEDEP}] )
	izone? ( ~dev-python/python-izone-1.2.9[${PYTHON_USEDEP}] )
	jellyfin? ( ~dev-python/jellyfin-apiclient-python-1.10.0[${PYTHON_USEDEP}] )
	jewish-calendar? ( ~dev-python/hdate-1.1.0[astral,${PYTHON_USEDEP}] )
	joaoapps-join? ( ~dev-python/python-join-api-0.0.9[${PYTHON_USEDEP}] )
	juicenet? ( ~dev-python/python-juicenet-1.1.0[${PYTHON_USEDEP}] )
	justnimbus? ( ~dev-python/justnimbus-0.7.4[${PYTHON_USEDEP}] )
	jvc-projector? ( ~dev-python/pyjvcprojector-1.1.2[${PYTHON_USEDEP}] )
	kaiterra? ( ~dev-python/kaiterra-async-client-1.0.0[${PYTHON_USEDEP}] )
	kaleidescape? ( ~dev-python/pykaleidescape-1.0.1[${PYTHON_USEDEP}] )
	keba? ( ~dev-python/keba-kecontact-1.3.0[${PYTHON_USEDEP}] )
	keenetic-ndms2? ( ~dev-python/ndms2-client-0.1.2[${PYTHON_USEDEP}] )
	kef? ( ~dev-python/aiokef-0.2.16[${PYTHON_USEDEP}] ~dev-python/getmac-0.9.5[${PYTHON_USEDEP}] )
	kegtron? ( ~dev-python/kegtron-ble-0.4.0[${PYTHON_USEDEP}] )
	keyboard? ( ~dev-python/pyvera-0.3.15[${PYTHON_USEDEP}] )
	keyboard-remote? ( ~dev-python/asyncinotify-4.2.0[${PYTHON_USEDEP}] ~dev-python/evohome-async-1.0.5[${PYTHON_USEDEP}] )
	keymitt-ble? ( ~dev-python/pymicrobot-0.0.17[${PYTHON_USEDEP}] )
	kira? ( ~dev-python/pykira-0.1.1[${PYTHON_USEDEP}] )
	kiwi? ( ~dev-python/kiwiki-client-0.1.1[${PYTHON_USEDEP}] )
	kmtronic? ( ~dev-python/pykmtronic-0.3.0[${PYTHON_USEDEP}] )
	knocki? ( ~dev-python/knocki-0.4.2[${PYTHON_USEDEP}] )
	knx? ( ~dev-python/knx-frontend-2025.3.8.214559[${PYTHON_USEDEP}] ~dev-python/xknx-3.6.0[${PYTHON_USEDEP}] ~dev-python/xknxproject-3.8.2[${PYTHON_USEDEP}] )
	kodi? ( ~dev-python/pykodi-0.2.7[${PYTHON_USEDEP}] )
	konnected? ( ~dev-python/konnected-1.2.0[${PYTHON_USEDEP}] )
	kostal-plenticore? ( ~dev-python/pykoplenti-1.3.0[${PYTHON_USEDEP}] )
	kraken? ( ~dev-python/krakenex-2.2.2[${PYTHON_USEDEP}] ~dev-python/pykrakenapi-0.1.8[${PYTHON_USEDEP}] )
	kulersky? ( ~dev-python/pykulersky-0.5.8[${PYTHON_USEDEP}] )
	kwb? ( ~dev-python/pykwb-0.0.8[${PYTHON_USEDEP}] )
	lacrosse? ( ~dev-python/pylacrosse-0.4[${PYTHON_USEDEP}] )
	lacrosse-view? ( ~dev-python/lacrosse-view-1.1.1[${PYTHON_USEDEP}] )
	lamarzocco? ( ~dev-python/pylamarzocco-2.0.3[${PYTHON_USEDEP}] )
	lametric? ( ~dev-python/demetriek-1.2.0[${PYTHON_USEDEP}] )
	landisgyr-heat-meter? ( ~dev-python/ultraheat-api-0.5.7[${PYTHON_USEDEP}] )
	lastfm? ( ~dev-python/pylast-5.1.0[${PYTHON_USEDEP}] )
	launch-library? ( ~dev-python/pylaunches-2.0.0[${PYTHON_USEDEP}] )
	laundrify? ( ~dev-python/laundrify-aio-1.2.2[${PYTHON_USEDEP}] )
	lcn? ( ~dev-python/lcn-frontend-0.2.4[${PYTHON_USEDEP}] ~dev-python/pypck-0.8.5[${PYTHON_USEDEP}] )
	ld2410-ble? ( ~dev-python/bluetooth-data-tools-1.28.1[${PYTHON_USEDEP}] ~dev-python/ld2410-ble-0.1.1[${PYTHON_USEDEP}] )
	leaone? ( ~dev-python/leaone-ble-0.3.0[${PYTHON_USEDEP}] )
	led-ble? ( ~dev-python/bluetooth-data-tools-1.28.1[${PYTHON_USEDEP}] ~dev-python/led-ble-1.1.7[${PYTHON_USEDEP}] )
	lektrico? ( ~dev-python/lektricowifi-0.0.43[${PYTHON_USEDEP}] )
	letpot? ( ~dev-python/letpot-0.4.0[${PYTHON_USEDEP}] )
	lg-netcast? ( ~dev-python/pylgnetcast-0.3.9[${PYTHON_USEDEP}] )
	lg-soundbar? ( ~dev-python/temescal-0.5[${PYTHON_USEDEP}] )
	lg-thinq? ( ~dev-python/thinqconnect-1.0.5[${PYTHON_USEDEP}] )
	lidarr? ( ~dev-python/aiopyarr-23.4.0[${PYTHON_USEDEP}] )
	lifx? ( ~dev-python/aiolifx-effects-0.3.2[${PYTHON_USEDEP}] ~dev-python/aiolifx-themes-0.6.4[${PYTHON_USEDEP}] ~dev-python/aiolifx-1.1.4[${PYTHON_USEDEP}] )
	lightwave? ( ~dev-python/lightwave-0.24[${PYTHON_USEDEP}] )
	limitlessled? ( ~dev-python/limitlessled-1.1.3[${PYTHON_USEDEP}] )
	linear-garage-door? ( ~dev-python/linear-garage-door-0.2.9[${PYTHON_USEDEP}] )
	linkplay? ( ~dev-python/python-linkplay-0.2.5[${PYTHON_USEDEP}] )
	linode? ( ~dev-python/linode-api-4.1.9_beta1[${PYTHON_USEDEP}] )
	linux-battery? ( ~dev-python/batinfo-0.4.2[${PYTHON_USEDEP}] )
	lirc? ( ~dev-python/python-matter-server-7.0.0[${PYTHON_USEDEP}] )
	litejet? ( ~dev-python/pylitejet-0.6.3[${PYTHON_USEDEP}] )
	litterrobot? ( ~dev-python/pylitterbot-2024.0.0[${PYTHON_USEDEP}] )
	livisi? ( ~dev-python/livisi-0.0.25[${PYTHON_USEDEP}] )
	local-calendar? ( ~dev-python/ical-9.2.4[${PYTHON_USEDEP}] )
	local-todo? ( ~dev-python/ical-9.2.4[${PYTHON_USEDEP}] )
	london-underground? ( ~dev-python/london-tube-status-0.5[${PYTHON_USEDEP}] )
	lookin? ( ~dev-python/aiolookin-1.0.0[${PYTHON_USEDEP}] )
	loqed? ( ~dev-python/loqedapi-2.1.10[${PYTHON_USEDEP}] )
	luci? ( ~dev-python/openwrt-luci-rpc-1.1.17[${PYTHON_USEDEP}] )
	luftdaten? ( ~dev-python/luftdaten-0.7.4[${PYTHON_USEDEP}] )
	lupusec? ( ~dev-python/lupupy-0.3.2[${PYTHON_USEDEP}] )
	lutron-caseta? ( ~dev-python/pylutron-caseta-0.24.0[${PYTHON_USEDEP}] )
	lutron? ( ~dev-python/pylutron-0.2.18[${PYTHON_USEDEP}] )
	lw12wifi? ( ~dev-python/lw12-0.9.2[${PYTHON_USEDEP}] )
	lyric? ( ~dev-python/aiolyric-2.0.1[${PYTHON_USEDEP}] )
	madvr? ( ~dev-python/py-madvr2-1.6.32[${PYTHON_USEDEP}] )
	mailgun? ( ~dev-python/pymailgunner-1.4[${PYTHON_USEDEP}] )
	marytts? ( ~dev-python/speak2mary-1.4.0[${PYTHON_USEDEP}] )
	mastodon? ( ~dev-python/mastodon-py-2.0.1[${PYTHON_USEDEP}] )
	matrix? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/matrix-nio-0.25.2[${PYTHON_USEDEP}] )
	matter? ( ~dev-python/python-matter-server-7.0.0[${PYTHON_USEDEP}] )
	maxcube? ( ~dev-python/maxcube-api-0.4.3[${PYTHON_USEDEP}] )
	mcp? ( ~dev-python/mcp-1.5.0[${PYTHON_USEDEP}] )
	mcp-server? ( ~dev-python/aiohttp-sse-2.2.0[${PYTHON_USEDEP}] ~dev-python/anyio-4.9.0[${PYTHON_USEDEP}] ~dev-python/mcp-1.5.0[${PYTHON_USEDEP}] )
	mealie? ( ~dev-python/aiomealie-0.9.5[${PYTHON_USEDEP}] )
	meater? ( ~dev-python/meater-python-0.0.8[${PYTHON_USEDEP}] )
	medcom-ble? ( ~dev-python/medcom-ble-0.1.1[${PYTHON_USEDEP}] )
	media-extractor? ( ~net-misc/yt-dlp-2025.03.31[default,${PYTHON_USEDEP}] )
	mediaroom? ( ~dev-python/pymediaroom-0.6.5.4[${PYTHON_USEDEP}] )
	melcloud? ( ~dev-python/python-melcloud-0.1.0[${PYTHON_USEDEP}] )
	melissa? ( ~dev-python/py-melissa-climate-2.1.4[${PYTHON_USEDEP}] )
	melnor? ( ~dev-python/melnor-bluetooth-0.0.25[${PYTHON_USEDEP}] )
	message-bird? ( ~dev-python/messagebird-1.2.0[${PYTHON_USEDEP}] )
	met-eireann? ( ~dev-python/pymeteireann-2024.11.0[${PYTHON_USEDEP}] )
	meteoalarm? ( ~dev-python/meteoalertapi-0.3.1[${PYTHON_USEDEP}] )
	meteoclimatic? ( ~dev-python/pymeteoclimatic-0.1.0[${PYTHON_USEDEP}] )
	meteo-france? ( ~dev-python/meteofrance-api-1.4.0[${PYTHON_USEDEP}] )
	met? ( ~dev-python/pymetno-0.13.0[${PYTHON_USEDEP}] )
	metoffice? ( ~dev-python/datapoint-0.9.9[${PYTHON_USEDEP}] )
	mfi? ( ~dev-python/mficlient-0.5.0[${PYTHON_USEDEP}] )
	microbees? ( ~dev-python/microbeespy-0.3.5[${PYTHON_USEDEP}] )
	microsoft? ( ~dev-python/pycsspeechtts-1.0.8[${PYTHON_USEDEP}] )
	miele? ( ~dev-python/pymiele-0.4.3[${PYTHON_USEDEP}] )
	mikrotik? ( ~dev-python/librouteros-3.2.0[${PYTHON_USEDEP}] )
	mill? ( ~dev-python/mill-local-0.3.0[${PYTHON_USEDEP}] ~dev-python/millheater-0.12.5[${PYTHON_USEDEP}] )
	minecraft-server? ( ~dev-python/mcstatus-11.1.1[${PYTHON_USEDEP}] )
	minio? ( ~dev-python/minio-7.1.12[${PYTHON_USEDEP}] )
	moat? ( ~dev-python/moat-ble-0.1.1[${PYTHON_USEDEP}] )
	mobile-app? ( ~dev-python/pynacl-1.5.0[${PYTHON_USEDEP}] )
	mochad? ( ~dev-python/pymochad-0.2.0[${PYTHON_USEDEP}] )
	modbus? ( ~dev-python/pymodbus-3.8.3[${PYTHON_USEDEP}] )
	modem-callerid? ( ~dev-python/phone-modem-0.1.1[${PYTHON_USEDEP}] )
	modern-forms? ( ~dev-python/aiomodernforms-0.1.8[${PYTHON_USEDEP}] )
	moehlenhoff-alpha2? ( ~dev-python/moehlenhoff-alpha2-1.4.0[${PYTHON_USEDEP}] )
	monarch-money? ( ~dev-python/typedmonarchmoney-0.4.4[${PYTHON_USEDEP}] )
	monoprice? ( ~dev-python/pymonoprice-0.4[${PYTHON_USEDEP}] )
	monzo? ( ~dev-python/monzopy-1.4.2[${PYTHON_USEDEP}] )
	mopeka? ( ~dev-python/mopeka-iot-ble-0.8.0[${PYTHON_USEDEP}] )
	motionblinds-ble? ( ~dev-python/motionblindsble-0.1.3[${PYTHON_USEDEP}] )
	motion-blinds? ( ~dev-python/motionblinds-0.6.26[${PYTHON_USEDEP}] )
	motioneye? ( ~dev-python/motioneye-client-0.3.14[${PYTHON_USEDEP}] )
	motionmount? ( ~dev-python/python-motionmount-2.3.0[${PYTHON_USEDEP}] )
	mpd? ( ~dev-python/python-mpd2-3.1.1[${PYTHON_USEDEP}] )
	mqtt? ( ~dev-python/paho-mqtt-2.1.0[${PYTHON_USEDEP}] )
	msteams? ( ~dev-python/pymsteams-0.1.12[${PYTHON_USEDEP}] )
	mullvad? ( ~dev-python/mullvad-api-1.0.0[${PYTHON_USEDEP}] )
	music-assistant? ( ~dev-python/music-assistant-client-1.2.0[${PYTHON_USEDEP}] )
	mutesync? ( ~dev-python/mutesync-0.0.1[${PYTHON_USEDEP}] )
	mysensors? ( ~dev-python/pymysensors-0.24.0[${PYTHON_USEDEP}] )
	mystrom? ( ~dev-python/python-mystrom-2.2.0[${PYTHON_USEDEP}] )
	mythicbeastsdns? ( ~dev-python/mbddns-0.1.2[${PYTHON_USEDEP}] )
	myuplink? ( ~dev-python/myuplink-0.7.0[${PYTHON_USEDEP}] )
	nad? ( ~dev-python/nad-receiver-0.3.0[${PYTHON_USEDEP}] )
	namecheapdns? ( =dev-python/defusedxml-0.7.1-r1[${PYTHON_USEDEP}] )
	nam? ( ~dev-python/nettigo-air-monitor-4.1.0[${PYTHON_USEDEP}] )
	nanoleaf? ( ~dev-python/aionanoleaf-0.2.1[${PYTHON_USEDEP}] )
	nasweb? ( ~dev-python/webio-api-0.1.11[${PYTHON_USEDEP}] )
	neato? ( ~dev-python/pybotvac-0.0.26[${PYTHON_USEDEP}] )
	nederlandse-spoorwegen? ( ~dev-python/nsapi-3.1.2[${PYTHON_USEDEP}] )
	ness-alarm? ( ~dev-python/nessclient-1.1.2[${PYTHON_USEDEP}] )
	nest? ( ~dev-python/google-nest-sdm-7.1.4[${PYTHON_USEDEP}] )
	netatmo? ( ~dev-python/pyatmo-9.0.0[${PYTHON_USEDEP}] )
	netdata? ( ~dev-python/netdata-1.3.0[${PYTHON_USEDEP}] )
	netgear-lte? ( ~dev-python/eternalegypt-0.0.16[${PYTHON_USEDEP}] )
	netgear? ( ~dev-python/pynetgear-0.10.10[${PYTHON_USEDEP}] )
	netio? ( ~dev-python/pynetio-0.1.9.1[${PYTHON_USEDEP}] )
	network? ( ~dev-python/ifaddr-0.2.0[${PYTHON_USEDEP}] )
	neurio-energy? ( ~dev-python/neurio-0.3.1[${PYTHON_USEDEP}] )
	nexia? ( ~dev-python/nexia-2.7.0[${PYTHON_USEDEP}] )
	nextbus? ( ~dev-python/py-nextbusnext-2.1.2[${PYTHON_USEDEP}] )
	nextcloud? ( ~dev-python/nextcloudmonitor-1.5.1[${PYTHON_USEDEP}] )
	nextdns? ( ~dev-python/nextdns-4.0.0[${PYTHON_USEDEP}] )
	nfandroidtv? ( ~dev-python/notifications-android-tv-0.1.5[${PYTHON_USEDEP}] )
	nibe-heatpump? ( ~dev-python/nibe-2.17.0[${PYTHON_USEDEP}] )
	nice-go? ( ~dev-python/nice-go-1.0.1[${PYTHON_USEDEP}] )
	nightscout? ( ~dev-python/py-nightscout-1.2.2[${PYTHON_USEDEP}] )
	niko-home-control? ( ~dev-python/nhc-0.4.10[${PYTHON_USEDEP}] )
	nilu? ( ~dev-python/niluclient-0.1.2[${PYTHON_USEDEP}] )
	nina? ( ~dev-python/pynina-0.3.5[${PYTHON_USEDEP}] )
	nissan-leaf? ( ~dev-python/pycarwings2-2.14[${PYTHON_USEDEP}] )
	nmap-tracker? ( ~dev-python/aiooui-0.1.9[${PYTHON_USEDEP}] ~dev-python/getmac-0.9.5[${PYTHON_USEDEP}] ~dev-python/netmap-0.7.0.2[${PYTHON_USEDEP}] )
	nmbs? ( ~dev-python/pyrail-0.4.1[${PYTHON_USEDEP}] )
	noaa-tides? ( ~dev-python/noaa-coops-0.4.0[${PYTHON_USEDEP}] )
	nobo-hub? ( ~dev-python/pynobo-1.8.1[${PYTHON_USEDEP}] )
	nordpool? ( ~dev-python/pynordpool-0.2.4[${PYTHON_USEDEP}] )
	norway-air? ( ~dev-python/pymetno-0.13.0[${PYTHON_USEDEP}] )
	notify-events? ( ~dev-python/notify-events-1.0.4[${PYTHON_USEDEP}] )
	notion? ( ~dev-python/aionotion-2024.3.0[${PYTHON_USEDEP}] )
	nsw-fuel-station? ( ~dev-python/nsw-fuel-api-client-1.1.0[${PYTHON_USEDEP}] )
	nsw-rural-fire-service-feed? ( ~dev-python/aio-geojson-nsw-rfs-incidents-0.7[${PYTHON_USEDEP}] )
	ntfy? ( ~dev-python/aiontfy-0.5.1[${PYTHON_USEDEP}] )
	nuheat? ( ~dev-python/nuheat-1.0.1[${PYTHON_USEDEP}] )
	nuki? ( ~dev-python/pynuki-1.6.3[${PYTHON_USEDEP}] )
	numato? ( ~dev-python/numato-gpio-0.13.0[${PYTHON_USEDEP}] )
	nut? ( ~dev-python/aionut-4.3.4[${PYTHON_USEDEP}] )
	nws? ( ~dev-python/pynws-1.8.2[retry,${PYTHON_USEDEP}] )
	nx584? ( ~dev-python/pynx584-0.8.2[${PYTHON_USEDEP}] )
	nyt-games? ( ~dev-python/nyt-games-0.4.4[${PYTHON_USEDEP}] )
	nzbget? ( ~dev-python/pynzbgetapi-0.2.0[${PYTHON_USEDEP}] )
	oasa-telematics? ( ~dev-python/oasatelematics-0.3[${PYTHON_USEDEP}] )
	obihai? ( ~dev-python/pyobihai-1.4.2[${PYTHON_USEDEP}] )
	octoprint? ( ~dev-python/pyoctoprintapi-0.1.12[${PYTHON_USEDEP}] )
	oem? ( ~dev-python/oemthermostat-1.1.1[${PYTHON_USEDEP}] )
	ohmconnect? ( =dev-python/defusedxml-0.7.1-r1[${PYTHON_USEDEP}] )
	ohme? ( ~dev-python/ohme-1.5.1[${PYTHON_USEDEP}] )
	ollama? ( ~dev-python/ollama-0.4.7[${PYTHON_USEDEP}] )
	ombi? ( ~dev-python/pyombi-0.1.10[${PYTHON_USEDEP}] )
	omnilogic? ( ~dev-python/omnilogic-0.4.5[${PYTHON_USEDEP}] )
	ondilo-ico? ( ~dev-python/ondilo-0.5.0[${PYTHON_USEDEP}] )
	onedrive? ( ~dev-python/onedrive-personal-sdk-0.0.14[${PYTHON_USEDEP}] )
	onewire? ( ~dev-python/pyownet-0.10.0_p1[${PYTHON_USEDEP}] )
	onkyo? ( ~dev-python/pyeiscp-0.0.7[${PYTHON_USEDEP}] )
	onvif? ( ~dev-python/wsdiscovery-2.1.2[${PYTHON_USEDEP}] ~dev-python/onvif-zeep-async-3.2.5[${PYTHON_USEDEP}] )
	openai-conversation? ( ~dev-python/openai-1.76.2[${PYTHON_USEDEP}] )
	openerz? ( ~dev-python/openerz-api-0.3.0[${PYTHON_USEDEP}] )
	openevse? ( ~dev-python/openevsewifi-1.1.2[${PYTHON_USEDEP}] )
	openexchangerates? ( ~dev-python/aioopenexchangerates-0.6.8[${PYTHON_USEDEP}] )
	opengarage? ( ~dev-python/open-garage-0.2.0[${PYTHON_USEDEP}] )
	openhome? ( ~dev-python/openhomedevice-2.2[${PYTHON_USEDEP}] )
	open-meteo? ( ~dev-python/open-meteo-0.3.2[${PYTHON_USEDEP}] )
	opensensemap? ( ~dev-python/opensensemap-api-0.2.0[${PYTHON_USEDEP}] )
	opensky? ( ~dev-python/python-opensky-1.0.1[${PYTHON_USEDEP}] )
	opentherm-gw? ( ~dev-python/pyotgw-2.2.2[${PYTHON_USEDEP}] )
	openuv? ( ~dev-python/pyopenuv-2023.2.0[${PYTHON_USEDEP}] )
	openweathermap? ( ~dev-python/pyopenweathermap-0.2.2[${PYTHON_USEDEP}] )
	opnsense? ( ~dev-python/pyopnsense-0.4.0[${PYTHON_USEDEP}] )
	opower? ( ~dev-python/opower-0.12.0[${PYTHON_USEDEP}] )
	opple? ( ~dev-python/pyoppleio-legacy-1.0.8[${PYTHON_USEDEP}] )
	oralb? ( ~dev-python/oralb-ble-0.17.6[${PYTHON_USEDEP}] )
	oru? ( ~dev-python/oru-0.1.11[${PYTHON_USEDEP}] )
	orvibo? ( ~dev-python/orvibo-1.1.2[${PYTHON_USEDEP}] )
	osoenergy? ( ~dev-python/pyosoenergyapi-1.1.4[${PYTHON_USEDEP}] )
	osramlightify? ( ~dev-python/lightify-1.0.7.3[${PYTHON_USEDEP}] )
	otbr? ( ~dev-python/python-otbr-api-2.7.0[${PYTHON_USEDEP}] )
	otp? ( ~dev-python/pyotp-2.8.0[${PYTHON_USEDEP}] )
	ourgroceries? ( ~dev-python/ourgroceries-1.5.4[${PYTHON_USEDEP}] )
	overkiz? ( ~dev-python/pyoverkiz-1.17.1[${PYTHON_USEDEP}] )
	overseerr? ( ~dev-python/python-overseerr-0.7.1[${PYTHON_USEDEP}] )
	ovo-energy? ( ~dev-python/ovoenergy-2.0.0[${PYTHON_USEDEP}] )
	owntracks? ( ~dev-python/pynacl-1.5.0[${PYTHON_USEDEP}] )
	p1-monitor? ( ~dev-python/p1monitor-3.1.0[${PYTHON_USEDEP}] )
	palazzetti? ( ~dev-python/pypalazzetti-0.1.19[${PYTHON_USEDEP}] )
	panasonic-bluray? ( ~dev-python/panacotta-0.2[${PYTHON_USEDEP}] )
	panasonic-viera? ( ~dev-python/panasonic-viera-0.4.2[${PYTHON_USEDEP}] )
	pandora? ( ~dev-python/pexpect-4.9.0[${PYTHON_USEDEP}] )
	peblar? ( ~dev-python/peblar-0.4.0[${PYTHON_USEDEP}] )
	peco? ( ~dev-python/peco-0.1.2[${PYTHON_USEDEP}] )
	pegel-online? ( ~dev-python/aiopegelonline-0.1.1[${PYTHON_USEDEP}] )
	pencom? ( ~dev-python/pencompy-0.0.3[${PYTHON_USEDEP}] )
	permobil? ( ~dev-python/mypermobil-0.1.8[${PYTHON_USEDEP}] )
	pglab? ( ~dev-python/pypglab-0.0.5[${PYTHON_USEDEP}] )
	philips-js? ( ~dev-python/ha-philipsjs-3.2.2[${PYTHON_USEDEP}] )
	picnic? ( ~dev-python/python-picnic-api-1.2.4[${PYTHON_USEDEP}] )
	pi-hole? ( ~dev-python/hole-0.8.0[${PYTHON_USEDEP}] )
	pilight? ( ~dev-python/pilight-0.1.1[${PYTHON_USEDEP}] )
	ping? ( >=dev-python/icmplib-3.0.0[${PYTHON_USEDEP}] )
	pjlink? ( ~dev-python/pypjlink2-1.2.1[${PYTHON_USEDEP}] )
	plaato? ( ~dev-python/pyplaato-0.0.19[${PYTHON_USEDEP}] )
	plex? ( ~dev-python/plexapi-4.15.16[${PYTHON_USEDEP}] ~dev-python/plexauth-0.0.6[${PYTHON_USEDEP}] ~dev-python/plexwebsocket-0.0.14[${PYTHON_USEDEP}] )
	plugwise? ( ~dev-python/plugwise-1.7.3[${PYTHON_USEDEP}] )
	plum-lightpad? ( ~dev-python/plumlightpad-0.0.11[${PYTHON_USEDEP}] )
	pocketcasts? ( ~dev-python/pycketcasts-1.0.1[${PYTHON_USEDEP}] )
	point? ( ~dev-python/pypoint-3.0.0[${PYTHON_USEDEP}] )
	poolsense? ( ~dev-python/poolsense-0.0.8[${PYTHON_USEDEP}] )
	powerfox? ( ~dev-python/powerfox-1.2.1[${PYTHON_USEDEP}] )
	powerwall? ( ~dev-python/tesla-powerwall-0.5.2[${PYTHON_USEDEP}] )
	private-ble-device? ( ~dev-python/bluetooth-data-tools-1.28.1[${PYTHON_USEDEP}] )
	profiler? ( ~dev-python/guppy3-3.1.5[${PYTHON_USEDEP}] ~dev-python/objgraph-3.5.0[${PYTHON_USEDEP}] ~dev-python/pyprof2calltree-1.4.5[${PYTHON_USEDEP}] )
	progettihwsw? ( ~dev-python/progettihwsw-0.1.3[${PYTHON_USEDEP}] )
	proliphix? ( ~dev-python/proliphix-0.4.1[${PYTHON_USEDEP}] )
	prometheus? ( ~dev-python/prometheus-client-0.21.0[${PYTHON_USEDEP}] )
	prosegur? ( ~dev-python/pyprosegur-0.0.14[${PYTHON_USEDEP}] )
	proxmoxve? ( ~dev-python/proxmoxer-2.0.1[${PYTHON_USEDEP}] )
	proxy? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] )
	prusalink? ( ~dev-python/pyprusalink-2.1.1[${PYTHON_USEDEP}] )
	ps4? ( ~dev-python/pyps4-2ndscreen-1.3.1[${PYTHON_USEDEP}] )
	pterodactyl? ( ~dev-python/py-dactyl-2.0.4[${PYTHON_USEDEP}] )
	pulseaudio-loopback? ( ~dev-python/pulsectl-23.5.2[${PYTHON_USEDEP}] )
	pure-energie? ( ~dev-python/gridnet-5.0.1[${PYTHON_USEDEP}] )
	purpleair? ( ~dev-python/aiopurpleair-2023.12.0[${PYTHON_USEDEP}] )
	pushbullet? ( ~dev-python/pushbullet-py-0.11.0[${PYTHON_USEDEP}] )
	pushover? ( ~dev-python/pushover-complete-1.2.0[${PYTHON_USEDEP}] )
	pvoutput? ( ~dev-python/pvo-2.2.1[${PYTHON_USEDEP}] )
	pvpc-hourly-pricing? ( ~dev-python/aiopvpc-4.2.2[${PYTHON_USEDEP}] )
	pyload? ( ~dev-python/pyloadapi-1.4.2[${PYTHON_USEDEP}] )
	python-script? ( ~dev-python/restrictedpython-8.0[${PYTHON_USEDEP}] )
	qbittorrent? ( ~dev-python/qbittorrent-api-2024.9.67[${PYTHON_USEDEP}] )
	qbus? ( ~dev-python/qbusmqttapi-1.3.0[${PYTHON_USEDEP}] )
	qingping? ( ~dev-python/qingping-ble-0.10.0[${PYTHON_USEDEP}] )
	qld-bushfire? ( ~dev-python/georss-qld-bushfire-alert-client-0.8[${PYTHON_USEDEP}] )
	qnap? ( ~dev-python/qnapstats-0.4.0[${PYTHON_USEDEP}] )
	qnap-qsw? ( ~dev-python/aioqsw-0.4.1[${PYTHON_USEDEP}] )
	qrcode? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/pyzbar-0.1.7[${PYTHON_USEDEP}] )
	quantum-gateway? ( ~dev-python/quantum-gateway-0.0.8[${PYTHON_USEDEP}] )
	qvr-pro? ( ~dev-python/pyqvrpro-0.52[${PYTHON_USEDEP}] )
	qwikswitch? ( ~dev-python/pyqwikswitch-0.93[${PYTHON_USEDEP}] )
	rabbitair? ( ~dev-python/python-rabbitair-0.0.8[${PYTHON_USEDEP}] )
	rachio? ( ~dev-python/rachiopy-1.1.0[${PYTHON_USEDEP}] )
	radarr? ( ~dev-python/aiopyarr-23.4.0[${PYTHON_USEDEP}] )
	radio-browser? ( ~dev-python/pycountry-24.6.1[${PYTHON_USEDEP}] ~dev-python/radios-0.3.2[${PYTHON_USEDEP}] )
	radiotherm? ( ~dev-python/radiotherm-2.1.0[${PYTHON_USEDEP}] )
	rainbird? ( ~dev-python/pyrainbird-6.0.1[${PYTHON_USEDEP}] )
	raincloud? ( ~dev-python/raincloudy-0.0.7[${PYTHON_USEDEP}] )
	rainforest-eagle? ( ~dev-python/aioeagle-1.1.0[${PYTHON_USEDEP}] ~dev-python/eagle100-0.1.1[${PYTHON_USEDEP}] )
	rainforest-raven? ( ~dev-python/aioraven-0.7.1[${PYTHON_USEDEP}] )
	rainmachine? ( ~dev-python/regenmaschine-2024.3.0[${PYTHON_USEDEP}] )
	rapt-ble? ( ~dev-python/rapt-ble-0.1.2[${PYTHON_USEDEP}] )
	raspyrfm? ( ~dev-python/raspyrfm-client-1.2.8[${PYTHON_USEDEP}] )
	rdw? ( ~dev-python/vehicle-2.2.2[${PYTHON_USEDEP}] )
	recollect-waste? ( ~dev-python/aiorecollect-2023.9.0[${PYTHON_USEDEP}] )
	recorder? ( ~dev-python/sqlalchemy-2.0.40[${PYTHON_USEDEP}] ~dev-python/fnv-hash-fast-1.5.0[${PYTHON_USEDEP}] ~dev-python/psutil-home-assistant-0.0.1[${PYTHON_USEDEP}] )
	recswitch? ( ~dev-python/pyrecswitch-1.0.2[${PYTHON_USEDEP}] )
	reddit? ( ~dev-python/praw-7.5.0[${PYTHON_USEDEP}] )
	refoss? ( ~dev-python/refoss-ha-1.2.5[${PYTHON_USEDEP}] )
	rehlko? ( ~dev-python/aiokem-0.5.10[${PYTHON_USEDEP}] )
	rejseplanen? ( ~dev-python/rjpl-0.3.6[${PYTHON_USEDEP}] )
	remember-the-milk? ( ~dev-python/rtmapi-0.7.2[${PYTHON_USEDEP}] ~dev-python/httplib2-0.20.4[${PYTHON_USEDEP}] )
	remote-calendar? ( ~dev-python/ical-9.2.4[${PYTHON_USEDEP}] )
	remote-rpi-gpio? ( ~dev-python/gpiozero-1.6.2[${PYTHON_USEDEP}] ~dev-python/pigpio-1.78[${PYTHON_USEDEP}] )
	renault? ( ~dev-python/renault-api-0.3.1[${PYTHON_USEDEP}] )
	renson? ( ~dev-python/renson-endura-delta-1.7.2[${PYTHON_USEDEP}] )
	reolink? ( ~dev-python/reolink-aio-0.13.3[${PYTHON_USEDEP}] )
	repetier? ( ~dev-python/pyrepetierng-0.1.0[${PYTHON_USEDEP}] )
	rest? ( ~dev-python/jsonpath-0.82.2[${PYTHON_USEDEP}] >=dev-python/xmltodict-0.13.0[${PYTHON_USEDEP}] )
	rflink? ( ~dev-python/rflink-0.0.66[${PYTHON_USEDEP}] )
	rfxtrx? ( ~dev-python/pyrfxtrx-0.31.1[${PYTHON_USEDEP}] )
	ridwell? ( ~dev-python/aioridwell-2024.1.0[${PYTHON_USEDEP}] )
	ring? ( ~dev-python/ring-doorbell-0.9.13[${PYTHON_USEDEP}] )
	ripple? ( ~dev-python/python-ripple-api-0.0.3[${PYTHON_USEDEP}] )
	risco? ( ~dev-python/pyrisco-0.6.7[${PYTHON_USEDEP}] )
	rituals-perfume-genie? ( ~dev-python/pyrituals-0.0.6[${PYTHON_USEDEP}] )
	rmvtransport? ( ~dev-python/pyrmvtransport-0.3.3[${PYTHON_USEDEP}] )
	roborock? ( ~dev-python/python-roborock-2.18.2[${PYTHON_USEDEP}] ~dev-python/vacuum-map-parser-roborock-0.1.4[${PYTHON_USEDEP}] )
	rocketchat? ( ~dev-python/rocketchat-api-0.6.1[${PYTHON_USEDEP}] )
	roku? ( ~dev-python/rokuecp-0.19.3[${PYTHON_USEDEP}] )
	romy? ( ~dev-python/romy-0.0.10[${PYTHON_USEDEP}] )
	roomba? ( ~dev-python/roombapy-1.9.0[${PYTHON_USEDEP}] )
	roon? ( ~dev-python/roonapi-0.1.6[${PYTHON_USEDEP}] )
	route53? ( ~dev-python/boto3-1.37.1[${PYTHON_USEDEP}] )
	rova? ( ~dev-python/rova-0.4.1[${PYTHON_USEDEP}] )
	rpi-power? ( ~dev-python/rpi-bad-power-0.1.0[${PYTHON_USEDEP}] )
	ruckus-unleashed? ( ~dev-python/aioruckus-0.42[${PYTHON_USEDEP}] )
	russound-rio? ( ~dev-python/aiorussound-4.5.2[${PYTHON_USEDEP}] )
	russound-rnet? ( ~dev-python/russound-0.1.9[${PYTHON_USEDEP}] )
	ruuvi-gateway? ( ~dev-python/aioruuvigateway-0.1.0[${PYTHON_USEDEP}] )
	ruuvitag-ble? ( ~dev-python/ruuvitag-ble-0.1.2[${PYTHON_USEDEP}] )
	rympro? ( ~dev-python/pyrympro-0.0.9[${PYTHON_USEDEP}] )
	sabnzbd? ( ~dev-python/pysabnzbd-1.1.1[${PYTHON_USEDEP}] )
	saj? ( ~dev-python/pysaj-0.0.16[${PYTHON_USEDEP}] )
	samsungtv? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] ~dev-python/getmac-0.9.5[${PYTHON_USEDEP}] ~dev-python/samsungctl-0.7.1[websocket,${PYTHON_USEDEP}] ~dev-python/samsungtvws-2.7.2[async,encrypted,${PYTHON_USEDEP}] ~dev-python/wakeonlan-2.1.0[${PYTHON_USEDEP}] )
	sanix? ( ~dev-python/sanix-1.0.6[${PYTHON_USEDEP}] )
	satel-integra? ( ~dev-python/satel-integra-0.3.7[${PYTHON_USEDEP}] )
	schlage? ( ~dev-python/pyschlage-2025.4.0[${PYTHON_USEDEP}] )
	schluter? ( ~dev-python/py-schluter-0.1.7[${PYTHON_USEDEP}] )
	scrape? ( ~dev-python/beautifulsoup4-4.13.3[${PYTHON_USEDEP}] >=dev-python/lxml-5.3.0[${PYTHON_USEDEP}] )
	screenlogic? ( ~dev-python/screenlogicpy-0.10.0[${PYTHON_USEDEP}] )
	scsgate? ( ~dev-python/scsgate-0.1.0[${PYTHON_USEDEP}] )
	season? ( ~dev-python/ephem-4.1.6[${PYTHON_USEDEP}] )
	sendgrid? ( ~dev-python/sendgrid-6.8.2[${PYTHON_USEDEP}] )
	sense? ( ~dev-python/sense-energy-0.13.7[${PYTHON_USEDEP}] )
	sensibo? ( ~dev-python/pysensibo-1.2.1[${PYTHON_USEDEP}] )
	sensirion-ble? ( ~dev-python/sensirion-ble-0.1.1[${PYTHON_USEDEP}] )
	sensorpro? ( ~dev-python/sensorpro-ble-0.7.0[${PYTHON_USEDEP}] )
	sensorpush-cloud? ( ~dev-python/sensorpush-api-2.1.2[${PYTHON_USEDEP}] ~dev-python/sensorpush-ha-1.3.2[${PYTHON_USEDEP}] )
	sensorpush? ( ~dev-python/sensorpush-ble-1.9.0[${PYTHON_USEDEP}] )
	sensoterra? ( ~dev-python/sensoterra-2.0.1[${PYTHON_USEDEP}] )
	sentry? ( ~dev-python/sentry-sdk-1.45.1[${PYTHON_USEDEP}] )
	senz? ( ~dev-python/aiosenz-1.0.0[${PYTHON_USEDEP}] )
	serial? ( ~dev-python/pyserial-asyncio-fast-0.16[${PYTHON_USEDEP}] )
	serial-pm? ( ~dev-python/pmsensor-0.4[${PYTHON_USEDEP}] )
	sesame? ( ~dev-python/pysesame2-1.0.1[${PYTHON_USEDEP}] )
	seven-segments? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] )
	seventeentrack? ( ~dev-python/pyseventeentrack-1.0.2[${PYTHON_USEDEP}] )
	sfr-box? ( ~dev-python/sfrbox-api-0.0.11[${PYTHON_USEDEP}] )
	sharkiq? ( ~dev-python/sharkiq-1.1.0[${PYTHON_USEDEP}] )
	shelly? ( ~dev-python/aioshelly-13.6.0[${PYTHON_USEDEP}] )
	shodan? ( ~net-analyzer/shodan-1.28.0[${PYTHON_USEDEP}] )
	sia? ( ~dev-python/pysiaalarm-3.1.1[${PYTHON_USEDEP}] )
	sighthound? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/simplehound-0.3[${PYTHON_USEDEP}] )
	signal-messenger? ( ~dev-python/pysignalclirestapi-0.3.24[${PYTHON_USEDEP}] )
	simplefin? ( ~dev-python/simplefin4py-0.0.18[${PYTHON_USEDEP}] )
	simplepush? ( ~dev-python/simplepush-2.2.3[${PYTHON_USEDEP}] )
	simplisafe? ( ~dev-python/simplisafe-python-2024.1.0[${PYTHON_USEDEP}] )
	sinch? ( ~dev-python/clx-sdk-xms-1.0.0[${PYTHON_USEDEP}] )
	sisyphus? ( ~dev-python/sisyphus-control-3.1.4[${PYTHON_USEDEP}] )
	skybeacon? ( ~dev-python/pygatt-4.0.5[GATTTOOL,${PYTHON_USEDEP}] )
	skybell? ( ~dev-python/aioskybell-22.7.0[${PYTHON_USEDEP}] )
	sky-hub? ( ~dev-python/pyskyqhub-0.1.4[${PYTHON_USEDEP}] )
	sky-remote? ( ~dev-python/skyboxremote-0.0.6[${PYTHON_USEDEP}] )
	slack? ( ~dev-python/slack-sdk-3.33.4[${PYTHON_USEDEP}] )
	sleepiq? ( ~dev-python/asyncsleepiq-1.5.2[${PYTHON_USEDEP}] )
	slide-local? ( ~dev-python/goslide-api-0.7.0[${PYTHON_USEDEP}] )
	slide? ( ~dev-python/goslide-api-0.7.0[${PYTHON_USEDEP}] )
	slimproto? ( ~dev-python/aioslimproto-3.0.0[${PYTHON_USEDEP}] )
	sma? ( ~dev-python/pysma-0.7.5[${PYTHON_USEDEP}] )
	smappee? ( ~dev-python/pysmappee-0.2.29[${PYTHON_USEDEP}] )
	smart-meter-texas? ( ~dev-python/smart-meter-texas-0.5.5[${PYTHON_USEDEP}] )
	smartthings? ( ~dev-python/pysmartthings-3.2.2[${PYTHON_USEDEP}] )
	smarttub? ( ~dev-python/python-smarttub-0.0.39[${PYTHON_USEDEP}] )
	smarty? ( ~dev-python/pysmarty2-0.10.2[${PYTHON_USEDEP}] )
	smhi? ( ~dev-python/pysmhi-1.0.2[${PYTHON_USEDEP}] )
	smlight? ( ~dev-python/pysmlight-0.2.4[${PYTHON_USEDEP}] )
	sms? ( ~dev-python/python-gc100-1.0.3_alpha0[${PYTHON_USEDEP}] )
	snapcast? ( ~dev-python/snapcast-2.3.6[${PYTHON_USEDEP}] )
	snmp? ( ~dev-python/pysnmp-6.2.6[${PYTHON_USEDEP}] )
	snoo? ( ~dev-python/python-snoo-0.6.6[${PYTHON_USEDEP}] )
	snooz? ( ~dev-python/pysnooz-0.8.6[${PYTHON_USEDEP}] )
	solaredge-local? ( ~dev-python/solaredge-local-0.2.3[${PYTHON_USEDEP}] )
	solaredge? ( ~dev-python/aiosolaredge-0.2.0[${PYTHON_USEDEP}] ~dev-python/stringcase-1.2.0[${PYTHON_USEDEP}] )
	solarlog? ( ~dev-python/solarlog-cli-0.4.0[${PYTHON_USEDEP}] )
	solax? ( ~dev-python/solax-3.2.3[${PYTHON_USEDEP}] )
	soma? ( ~dev-python/pysoma-0.0.12[${PYTHON_USEDEP}] )
	somfy-mylink? ( ~dev-python/somfy-mylink-synergy-1.0.6[${PYTHON_USEDEP}] )
	sonarr? ( ~dev-python/aiopyarr-23.4.0[${PYTHON_USEDEP}] )
	songpal? ( ~dev-python/python-songpal-0.16.2[${PYTHON_USEDEP}] )
	sonos? ( ~dev-python/soco-0.30.9[${PYTHON_USEDEP}] ~dev-python/sonos-websocket-0.1.3[${PYTHON_USEDEP}] )
	sony-projector? ( ~dev-python/pysdcp-1[${PYTHON_USEDEP}] )
	soundtouch? ( >=dev-python/libsoundtouch-0.8.0[${PYTHON_USEDEP}] )
	spc? ( ~dev-python/pyspcwebgw-0.7.0[${PYTHON_USEDEP}] )
	speedtestdotnet? ( ~net-analyzer/speedtest-cli-2.1.3[${PYTHON_USEDEP}] )
	splunk? ( ~dev-python/hass-splunk-0.1.1[${PYTHON_USEDEP}] )
	spotify? ( ~dev-python/spotifyaio-0.8.11[${PYTHON_USEDEP}] )
	sql? ( ~dev-python/sqlalchemy-2.0.40[${PYTHON_USEDEP}] ~dev-python/sqlparse-0.5.0[${PYTHON_USEDEP}] )
	squeezebox? ( ~dev-python/pysqueezebox-0.12.0[${PYTHON_USEDEP}] )
	srp-energy? ( ~dev-python/srpenergy-1.3.6[${PYTHON_USEDEP}] )
	ssdp? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] )
	starline? ( ~dev-python/starline-0.1.5[${PYTHON_USEDEP}] )
	starlingbank? ( ~dev-python/starlingbank-3.2[${PYTHON_USEDEP}] )
	starlink? ( ~dev-python/starlink-grpc-core-1.2.2[${PYTHON_USEDEP}] )
	startca? ( >=dev-python/xmltodict-0.13.0[${PYTHON_USEDEP}] )
	statsd? ( ~dev-python/statsd-3.2.1[${PYTHON_USEDEP}] )
	steamist? ( ~dev-python/aiosteamist-1.0.1[${PYTHON_USEDEP}] ~dev-python/discovery30303-0.3.3[${PYTHON_USEDEP}] )
	steam-online? ( ~dev-python/steamodd-4.21[${PYTHON_USEDEP}] )
	stiebel-eltron? ( ~dev-python/pystiebeleltron-0.1.0[${PYTHON_USEDEP}] )
	stookwijzer? ( ~dev-python/stookwijzer-1.6.1[${PYTHON_USEDEP}] )
	streamlabswater? ( ~dev-python/streamlabswater-1.0.1[${PYTHON_USEDEP}] )
	stream? ( ~dev-python/pyturbojpeg-1.7.5[${PYTHON_USEDEP}] ~dev-python/av-13.1.0[${PYTHON_USEDEP}] ~dev-python/numpy-2.2.2[${PYTHON_USEDEP}] )
	subaru? ( ~dev-python/subarulink-0.7.13[${PYTHON_USEDEP}] )
	suez-water? ( ~dev-python/pysuezv2-2.0.4[${PYTHON_USEDEP}] )
	supla? ( ~dev-python/asyncpysupla-0.0.5[${PYTHON_USEDEP}] )
	surepetcare? ( ~dev-python/surepy-0.9.0[${PYTHON_USEDEP}] )
	swiss-hydrological-data? ( ~dev-python/swisshydrodata-0.1.0[${PYTHON_USEDEP}] )
	swiss-public-transport? ( ~dev-python/python-opendata-transport-0.5.0[${PYTHON_USEDEP}] )
	switchbee? ( ~dev-python/pyswitchbee-1.8.3[${PYTHON_USEDEP}] )
	switchbot-cloud? ( ~dev-python/switchbot-api-2.3.1[${PYTHON_USEDEP}] )
	switchbot? ( ~dev-python/pyswitchbot-0.60.1[${PYTHON_USEDEP}] )
	switcher-kis? ( ~dev-python/aioswitcher-6.0.0[${PYTHON_USEDEP}] )
	switchmate? ( ~dev-python/pyswitchmate-0.5.1[${PYTHON_USEDEP}] )
	syncthing? ( ~dev-python/aiosyncthing-0.5.1[${PYTHON_USEDEP}] )
	syncthru? ( ~dev-python/pysyncthru-0.8.0[${PYTHON_USEDEP}] ~dev-python/url-normalize-2.2.1[${PYTHON_USEDEP}] )
	synology-dsm? ( ~dev-python/py-synologydsm-api-2.7.1[${PYTHON_USEDEP}] )
	synology-srm? ( ~dev-python/synology-srm-0.2.0[${PYTHON_USEDEP}] )
	system-bridge? ( ~dev-python/systembridgeconnector-4.1.5[${PYTHON_USEDEP}] ~dev-python/systembridgemodels-4.2.4[${PYTHON_USEDEP}] )
	systemmonitor? ( ~dev-python/psutil-home-assistant-0.0.1[${PYTHON_USEDEP}] ~dev-python/psutil-7.0.0[${PYTHON_USEDEP}] )
	tado? ( ~dev-python/python-tado-0.18.14[${PYTHON_USEDEP}] )
	tailscale? ( ~dev-python/tailscale-0.6.2[${PYTHON_USEDEP}] )
	tailwind? ( ~dev-python/gotailwind-0.3.0[${PYTHON_USEDEP}] )
	tami4? ( ~dev-python/tami4edgeapi-3.0[${PYTHON_USEDEP}] )
	tankerkoenig? ( ~dev-python/aiotankerkoenig-0.4.2[${PYTHON_USEDEP}] )
	tank-utility? ( ~dev-python/tank-utility-1.5.0[${PYTHON_USEDEP}] )
	tapsaff? ( ~dev-python/tapsaff-0.2.1[${PYTHON_USEDEP}] )
	tasmota? ( ~dev-python/hatasmota-0.10.0[${PYTHON_USEDEP}] )
	tautulli? ( ~dev-python/pytautulli-23.1.1[${PYTHON_USEDEP}] )
	technove? ( ~dev-python/python-technove-2.0.0[${PYTHON_USEDEP}] )
	ted5000? ( >=dev-python/xmltodict-0.13.0[${PYTHON_USEDEP}] )
	tedee? ( ~dev-python/aiotedee-0.2.20[${PYTHON_USEDEP}] )
	telegram-bot? ( ~dev-python/python-telegram-bot-21.5[socks,${PYTHON_USEDEP}] )
	tellduslive? ( ~dev-python/tellduslive-0.10.12[${PYTHON_USEDEP}] )
	tellstick? ( ~dev-python/tellcore-net-0.4[${PYTHON_USEDEP}] ~dev-python/tellcore-py-1.1.2[${PYTHON_USEDEP}] )
	temper? ( ~dev-python/temperusb-1.6.1[${PYTHON_USEDEP}] )
	tensorflow? ( ~dev-python/pillow-11.2.1[${PYTHON_USEDEP}] ~dev-python/numpy-2.2.2[${PYTHON_USEDEP}] ~dev-python/pycomfoconnect-0.5.1[${PYTHON_USEDEP}] ~dev-python/tesla-fleet-api-1.0.17[${PYTHON_USEDEP}] ~dev-python/thermobeacon-ble-0.10.0[${PYTHON_USEDEP}] )
	tesla-fleet? ( ~dev-python/tesla-fleet-api-1.0.17[${PYTHON_USEDEP}] )
	tesla-wall-connector? ( ~dev-python/tesla-wall-connector-1.0.2[${PYTHON_USEDEP}] )
	teslemetry? ( ~dev-python/tesla-fleet-api-1.0.17[${PYTHON_USEDEP}] ~dev-python/teslemetry-stream-0.7.7[${PYTHON_USEDEP}] )
	tessie? ( ~dev-python/tesla-fleet-api-1.0.17[${PYTHON_USEDEP}] ~dev-python/tessie-api-0.1.1[${PYTHON_USEDEP}] )
	thermobeacon? ( ~dev-python/thermobeacon-ble-0.10.0[${PYTHON_USEDEP}] )
	thermopro? ( ~dev-python/thermopro-ble-0.13.0[${PYTHON_USEDEP}] )
	thethingsnetwork? ( ~dev-python/ttn-client-1.2.0[${PYTHON_USEDEP}] )
	thingspeak? ( ~dev-python/thingspeak-1.0.0[${PYTHON_USEDEP}] )
	thinkingcleaner? ( ~dev-python/pythinkingcleaner-0.0.3[${PYTHON_USEDEP}] )
	thread? ( ~dev-python/pyroute2-0.7.5[${PYTHON_USEDEP}] ~dev-python/python-otbr-api-2.7.0[${PYTHON_USEDEP}] )
	tibber? ( ~dev-python/pytibber-0.31.2[${PYTHON_USEDEP}] )
	tikteck? ( ~dev-python/tikteck-0.4[${PYTHON_USEDEP}] )
	tile? ( ~dev-python/pytile-2024.12.0[${PYTHON_USEDEP}] )
	tilt-ble? ( ~dev-python/tilt-ble-0.2.3[${PYTHON_USEDEP}] )
	tmb? ( ~dev-python/tmb-0.0.4[${PYTHON_USEDEP}] )
	todoist? ( ~dev-python/todoist-api-python-2.1.7[${PYTHON_USEDEP}] )
	tolo? ( ~dev-python/tololib-1.2.2[${PYTHON_USEDEP}] )
	tomorrowio? ( ~dev-python/pytomorrowio-0.3.6[${PYTHON_USEDEP}] )
	toon? ( ~dev-python/toonapi-0.3.0[${PYTHON_USEDEP}] )
	totalconnect? ( ~dev-python/total-connect-client-2025.1.4[${PYTHON_USEDEP}] )
	touchline? ( ~dev-python/pytouchline-extended-0.4.5[${PYTHON_USEDEP}] )
	touchline-sl? ( ~dev-python/pytouchlinesl-0.3.0[${PYTHON_USEDEP}] )
	tplink-lte? ( ~dev-python/tp-connected-0.0.4[${PYTHON_USEDEP}] )
	tplink? ( ~dev-python/python-kasa-0.10.2[speedups,${PYTHON_USEDEP}] )
	tplink-omada? ( ~dev-python/tplink-omada-client-1.4.4[${PYTHON_USEDEP}] )
	traccar? ( ~dev-python/pytraccar-2.1.1[${PYTHON_USEDEP}] ~dev-python/stringcase-1.2.0[${PYTHON_USEDEP}] )
	traccar-server? ( ~dev-python/pytraccar-2.1.1[${PYTHON_USEDEP}] )
	tractive? ( ~dev-python/aiotractive-0.6.0[${PYTHON_USEDEP}] )
	tradfri? ( ~dev-python/pytradfri-9.0.1[async,${PYTHON_USEDEP}] )
	trafikverket-camera? ( ~dev-python/pytrafikverket-1.1.1[${PYTHON_USEDEP}] )
	trafikverket-ferry? ( ~dev-python/pytrafikverket-1.1.1[${PYTHON_USEDEP}] )
	trafikverket-train? ( ~dev-python/pytrafikverket-1.1.1[${PYTHON_USEDEP}] )
	trafikverket-weatherstation? ( ~dev-python/pytrafikverket-1.1.1[${PYTHON_USEDEP}] )
	transmission? ( ~dev-python/transmission-rpc-7.0.3[${PYTHON_USEDEP}] )
	transport-nsw? ( ~dev-python/pytransportnsw-0.1.1[${PYTHON_USEDEP}] )
	travisci? ( ~dev-python/travispy-0.3.5[${PYTHON_USEDEP}] )
	trend? ( ~dev-python/numpy-2.2.2[${PYTHON_USEDEP}] )
	triggercmd? ( ~dev-python/triggercmd-0.0.27[${PYTHON_USEDEP}] )
	tts? ( ~media-libs/mutagen-1.47.0[${PYTHON_USEDEP}] )
	tuya? ( ~dev-python/tuya-device-sharing-sdk-0.2.1[${PYTHON_USEDEP}] )
	twentemilieu? ( ~dev-python/twentemilieu-2.2.1[${PYTHON_USEDEP}] )
	twilio? ( ~dev-python/twilio-6.32.0[${PYTHON_USEDEP}] )
	twinkly? ( ~dev-python/ttls-1.8.3[${PYTHON_USEDEP}] )
	twitch? ( ~dev-python/twitchapi-4.2.1[${PYTHON_USEDEP}] )
	twitter? ( ~dev-python/twitterapi-2.7.12[${PYTHON_USEDEP}] )
	ubus? ( ~dev-python/openwrt-ubus-rpc-0.0.2[${PYTHON_USEDEP}] )
	ukraine-alarm? ( ~dev-python/uasiren-0.0.1[${PYTHON_USEDEP}] )
	unifi-direct? ( ~dev-python/unifi-ap-0.0.2[${PYTHON_USEDEP}] )
	unifiled? ( ~dev-python/unifiled-0.11[${PYTHON_USEDEP}] )
	unifi? ( ~dev-python/aiounifi-83[${PYTHON_USEDEP}] )
	unifiprotect? ( ~dev-python/uiprotect-7.6.0[${PYTHON_USEDEP}] ~dev-python/unifi-discovery-1.2.0[${PYTHON_USEDEP}] )
	upb? ( ~dev-python/upb-lib-0.6.1[${PYTHON_USEDEP}] )
	upc-connect? ( ~dev-python/connect-box-0.3.1[${PYTHON_USEDEP}] )
	upcloud? ( ~dev-python/upcloud-api-2.6.0[${PYTHON_USEDEP}] )
	upnp? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] ~dev-python/getmac-0.9.5[${PYTHON_USEDEP}] )
	uptimerobot? ( ~dev-python/pyuptimerobot-22.2.0[${PYTHON_USEDEP}] )
	usb? ( ~dev-python/aiousbwatcher-1.1.1[${PYTHON_USEDEP}] ~dev-python/pyserial-3.5[${PYTHON_USEDEP}] )
	usgs-earthquakes-feed? ( ~dev-python/aio-geojson-usgs-earthquakes-0.3[${PYTHON_USEDEP}] )
	utility-meter? ( ~dev-python/cronsim-2.6[${PYTHON_USEDEP}] )
	uvc? ( ~dev-python/uvcclient-0.12.1[${PYTHON_USEDEP}] )
	v2c? ( ~dev-python/pytrydan-0.8.0[${PYTHON_USEDEP}] )
	vallox? ( ~dev-python/vallox-websocket-api-5.3.0[${PYTHON_USEDEP}] )
	vasttrafik? ( ~dev-python/vtjp-0.2.1[${PYTHON_USEDEP}] )
	velbus? ( ~dev-python/velbus-aio-2025.4.2[${PYTHON_USEDEP}] )
	velux? ( ~dev-python/pyvlx-0.2.26[${PYTHON_USEDEP}] )
	venstar? ( ~dev-python/venstarcolortouch-0.19[${PYTHON_USEDEP}] )
	vera? ( ~dev-python/pyvera-0.3.15[${PYTHON_USEDEP}] )
	verisure? ( ~dev-python/vsure-2.6.7[${PYTHON_USEDEP}] )
	versasense? ( ~dev-python/pyversasense-0.0.6[${PYTHON_USEDEP}] )
	version? ( ~dev-python/pyhaversion-22.8.0[${PYTHON_USEDEP}] )
	vesync? ( ~dev-python/pyvesync-2.1.18[${PYTHON_USEDEP}] )
	vicare? ( ~dev-python/pyvicare-2.44.0[${PYTHON_USEDEP}] )
	vilfo? ( ~dev-python/vilfo-api-client-0.5.0[${PYTHON_USEDEP}] )
	vivotek? ( ~dev-python/libpyvivotek-0.4.0[${PYTHON_USEDEP}] )
	vizio? ( ~dev-python/pyvizio-0.1.61[${PYTHON_USEDEP}] )
	vlc? ( ~dev-python/python-vlc-3.0.18122[${PYTHON_USEDEP}] )
	vlc-telnet? ( ~dev-python/aiovlc-0.5.1[${PYTHON_USEDEP}] )
	vodafone-station? ( ~dev-python/aiovodafone-0.10.0[${PYTHON_USEDEP}] )
	voip? ( ~dev-python/voip-utils-0.3.2[${PYTHON_USEDEP}] )
	volkszaehler? ( ~dev-python/volkszaehler-0.4.0[${PYTHON_USEDEP}] )
	volumio? ( ~dev-python/pyvolumio-0.1.5[${PYTHON_USEDEP}] )
	volvooncall? ( ~dev-python/volvooncall-0.10.3[${PYTHON_USEDEP}] )
	vulcan? ( ~dev-python/vulcan-api-2.3.2[${PYTHON_USEDEP}] )
	vultr? ( ~dev-python/vultr-0.1.2[${PYTHON_USEDEP}] )
	w800rf32? ( ~dev-python/pyw800rf32-0.4[${PYTHON_USEDEP}] )
	wake-on-lan? ( ~dev-python/wakeonlan-2.1.0[${PYTHON_USEDEP}] )
	wallbox? ( ~dev-python/wallbox-0.9.0[${PYTHON_USEDEP}] )
	waqi? ( ~dev-python/aiowaqi-3.1.0[${PYTHON_USEDEP}] )
	waterfurnace? ( ~dev-python/waterfurnace-1.1.0[${PYTHON_USEDEP}] )
	watergate? ( ~dev-python/watergate-local-api-2024.4.1[${PYTHON_USEDEP}] )
	watson-iot? ( ~dev-python/ibmiotf-0.3.4[${PYTHON_USEDEP}] )
	watttime? ( ~dev-python/aiowatttime-0.1.1[${PYTHON_USEDEP}] )
	waze-travel-time? ( ~dev-python/pywaze-1.0.2[${PYTHON_USEDEP}] )
	weatherflow-cloud? ( ~dev-python/weatherflow4py-1.3.1[${PYTHON_USEDEP}] )
	weatherflow? ( ~dev-python/pyweatherflowudp-1.4.5[${PYTHON_USEDEP}] )
	weatherkit? ( ~dev-python/apple-weatherkit-1.1.3[${PYTHON_USEDEP}] )
	webdav? ( ~dev-python/aiowebdav2-0.4.5[${PYTHON_USEDEP}] )
	webmin? ( ~dev-python/webmin-xmlrpc-0.0.2[${PYTHON_USEDEP}] )
	webostv? ( ~dev-python/aiowebostv-0.7.3[${PYTHON_USEDEP}] )
	weheat? ( ~dev-python/weheat-2025.4.29[${PYTHON_USEDEP}] )
	wemo? ( ~dev-python/pywemo-1.4.0[${PYTHON_USEDEP}] )
	whirlpool? ( ~dev-python/whirlpool-sixth-sense-0.20.0[${PYTHON_USEDEP}] )
	whois? ( ~dev-python/whois-0.9.27[${PYTHON_USEDEP}] )
	wiffi? ( ~dev-python/wiffi-1.1.2[${PYTHON_USEDEP}] )
	wilight? ( ~dev-python/pywilight-0.0.74[${PYTHON_USEDEP}] )
	wirelesstag? ( ~dev-python/wirelesstagpy-0.8.1[${PYTHON_USEDEP}] )
	withings? ( ~dev-python/aiowithings-3.1.6[${PYTHON_USEDEP}] )
	wiz? ( ~dev-python/pywizlight-0.6.2[${PYTHON_USEDEP}] )
	wled? ( ~dev-python/wled-0.21.0[${PYTHON_USEDEP}] )
	wmspro? ( ~dev-python/pywmspro-0.2.2[${PYTHON_USEDEP}] )
	wolflink? ( ~dev-python/wolf-comm-0.0.23[${PYTHON_USEDEP}] )
	workday? ( ~dev-python/holidays-0.72[${PYTHON_USEDEP}] )
	ws66i? ( ~dev-python/pyws66i-1.1[${PYTHON_USEDEP}] )
	wyoming? ( ~dev-python/wyoming-1.5.4[${PYTHON_USEDEP}] )
	xbox? ( ~dev-python/xbox-webapi-2.1.0[${PYTHON_USEDEP}] )
	xeoma? ( ~dev-python/pyxeoma-1.4.2[${PYTHON_USEDEP}] )
	xiaomi-aqara? ( ~dev-python/pyxiaomigateway-0.14.3[${PYTHON_USEDEP}] )
	xiaomi-ble? ( ~dev-python/xiaomi-ble-0.38.0[${PYTHON_USEDEP}] )
	xiaomi-miio? ( ~dev-python/construct-2.10.68[${PYTHON_USEDEP}] ~dev-python/micloud-0.5[${PYTHON_USEDEP}] ~dev-python/python-miio-0.5.12[${PYTHON_USEDEP}] )
	xiaomi-tv? ( ~dev-python/pymitv-1.4.3[${PYTHON_USEDEP}] )
	xmpp? ( ~dev-python/emoji-2.8.0[${PYTHON_USEDEP}] ~dev-python/slixmpp-1.8.5[${PYTHON_USEDEP}] )
	xs1? ( ~dev-python/xs1-api-client-3.0.0[${PYTHON_USEDEP}] )
	yale? ( ~dev-python/yalexs-ble-2.6.0[${PYTHON_USEDEP}] ~dev-python/yalexs-8.10.0[${PYTHON_USEDEP}] )
	yale-smart-alarm? ( ~dev-python/yalesmartalarmclient-0.4.3[${PYTHON_USEDEP}] )
	yalexs-ble? ( ~dev-python/yalexs-ble-2.6.0[${PYTHON_USEDEP}] )
	yamaha? ( ~dev-python/rxv-0.7.0[${PYTHON_USEDEP}] )
	yamaha-musiccast? ( ~dev-python/aiomusiccast-0.14.8[${PYTHON_USEDEP}] )
	yandex-transport? ( ~dev-python/aioymaps-1.2.5[${PYTHON_USEDEP}] )
	yardian? ( ~dev-python/pyyardian-1.1.1[${PYTHON_USEDEP}] )
	yeelight? ( ~dev-python/async-upnp-client-0.44.0[${PYTHON_USEDEP}] ~dev-python/yeelight-0.7.16[${PYTHON_USEDEP}] )
	yeelightsunflower? ( ~dev-python/yeelightsunflower-0.0.10[${PYTHON_USEDEP}] )
	yi? ( ~dev-python/aioftp-0.21.3[${PYTHON_USEDEP}] )
	yolink? ( ~dev-python/yolink-api-0.5.2[${PYTHON_USEDEP}] )
	youless? ( ~dev-python/youless-api-2.2.0[${PYTHON_USEDEP}] )
	youtube? ( ~dev-python/youtubeaio-1.1.5[${PYTHON_USEDEP}] )
	zabbix? ( ~dev-python/zabbix-utils-2.0.2[${PYTHON_USEDEP}] )
	zamg? ( ~dev-python/zamg-0.3.6[${PYTHON_USEDEP}] )
	zeroconf? ( ~dev-python/zeroconf-0.147.0[${PYTHON_USEDEP}] )
	zerproc? ( ~dev-python/pyzerproc-0.4.8[${PYTHON_USEDEP}] )
	zestimate? ( >=dev-python/xmltodict-0.13.0[${PYTHON_USEDEP}] )
	zeversolar? ( ~dev-python/zeversolar-0.3.2[${PYTHON_USEDEP}] )
	zha? ( ~dev-python/zha-0.0.57[${PYTHON_USEDEP}] )
	zhong-hong? ( ~dev-python/zhong-hong-hvac-1.0.13[${PYTHON_USEDEP}] )
	ziggo-mediabox-xl? ( ~dev-python/ziggo-mediabox-xl-1.1.0[${PYTHON_USEDEP}] )
	zoneminder? ( ~dev-python/zm-py-0.5.4[${PYTHON_USEDEP}] )
	zwave-js? ( ~dev-python/pyserial-3.5[${PYTHON_USEDEP}] ~dev-python/zwave-js-server-python-0.63.0[${PYTHON_USEDEP}] )
	zwave-me? ( ~dev-python/url-normalize-2.2.1[${PYTHON_USEDEP}] ~dev-python/zwave-me-ws-0.4.3[${PYTHON_USEDEP}] )
"

BDEPEND="${RDEPEND}
	test? (
		dev-python/astroid[${PYTHON_USEDEP}]
		dev-python/coverage[${PYTHON_USEDEP}]
		dev-python/freezegun[${PYTHON_USEDEP}]
		dev-python/mock-open[${PYTHON_USEDEP}]
		dev-python/mypy-dev[${PYTHON_USEDEP}]
		dev-python/pipdeptree[${PYTHON_USEDEP}]
		dev-vcs/pre-commit
		dev-python/pylint-per-file-ignores[${PYTHON_USEDEP}]
		dev-python/pylint[${PYTHON_USEDEP}]
		dev-python/pytest-asyncio[${PYTHON_USEDEP}]
		dev-python/pytest-cov[${PYTHON_USEDEP}]
		dev-python/pytest-freezer[${PYTHON_USEDEP}]
		dev-python/pytest-github-actions-annotate-failures[${PYTHON_USEDEP}]
		dev-python/pytest-picked[${PYTHON_USEDEP}]
		dev-python/pytest-socket[${PYTHON_USEDEP}]
		dev-python/pytest-sugar[${PYTHON_USEDEP}]
		dev-python/pytest-timeout[${PYTHON_USEDEP}]
		dev-python/pytest-unordered[${PYTHON_USEDEP}]
		dev-python/pytest-xdist[${PYTHON_USEDEP}]
		dev-python/pytest[${PYTHON_USEDEP}]
		dev-python/requests-mock[${PYTHON_USEDEP}]
		dev-python/respx[${PYTHON_USEDEP}]
		dev-python/syrupy[${PYTHON_USEDEP}]
		dev-python/tqdm[${PYTHON_USEDEP}]
	)
	dev-python/setuptools[${PYTHON_USEDEP}]
	dev-python/mock[${PYTHON_USEDEP}]"

src_prepare() {
	if use test ; then
		cp --no-preserve=mode --recursive "${WORKDIR}/core-${MY_PV}/tests" "${S}"
		chmod u+x "${S}/tests/auth/providers/test_command_line_cmd.sh"
	fi
	sed -E -i "s/regex==[^ ]*/regex/g" -i "homeassistant/package_constraints.txt" || die

	distutils-r1_src_prepare
}
INSTALL_DIR="/opt/${MY_PN}"

DISABLE_AUTOFORMATTING=1
DOC_CONTENTS="
The HA interface listens on port 8123
hass configuration is in: /etc/${MY_PN}
daemon command line arguments are configured in: /etc/conf.d/${MY_PN}
logging is to: /var/log/${MY_PN}/{server,errors,stdout}.log
The sqlite db is by default in: /etc/${MY_PN}
support at https://git.edevau.net/onkelbeh/HomeAssistantRepository
"

DOCS="README.rst"

python_install_all() {
	dodoc ${DOCS}
	distutils-r1_python_install_all
	keepdir "$INSTALL_DIR"
	keepdir "/etc/${MY_PN}"
	fowners -R "${MY_PN}:${MY_PN}" "/etc/${MY_PN}"
	keepdir "/var/log/${MY_PN}"
	fowners -R "${MY_PN}:${MY_PN}" "/var/log/${MY_PN}"
	newconfd "${FILESDIR}/${MY_PN}.conf.d" "${MY_PN}"
	newinitd "${FILESDIR}/${MY_PN}.init.d" "${MY_PN}"
	use systemd && systemd_dounit "${FILESDIR}/${MY_PN}.service"
	dobin "${FILESDIR}/hasstest"
	if use socat ; then
		newinitd "${FILESDIR}/socat-zwave.init.d" "socat-zwave"
		sed -i -e 's/# need socat-zwave/need socat-zwave/g' "${D}/etc/init.d/${MY_PN}" || die
	fi
	if use mqtt ; then
		sed -i -e 's/# need mosquitto/need mosquitto/g' "${D}/etc/init.d/${MY_PN}" || die
	fi
	if use cli ; then
		echo -e "stop() {\n\tebegin Stoping homeassistant\n\thass-cli --token \${HASS_TOKEN} -s \${HASS_SERVER} service call homeassistant.stop\n\tsleep .5\n\tstart-stop-daemon -K \$command --pidfile \$pidfile\n\teend\n}" >> "${D}/etc/init.d/${MY_PN}"
	fi
	insinto /etc/logrotate.d
	newins "${FILESDIR}/${MY_PN}.logrotate" "${MY_PN}"
	readme.gentoo_create_doc
}

pkg_postinst() {
	readme.gentoo_print_elog
}

distutils_enable_tests pytest
