#/bin/bash
if [ -n $1 ]; then
  pkg="=$( pwd | rev | cut -d/ -f1-2 | rev )-$1"
else
  pkg=$( pwd | rev | cut -d/ -f1-2 | rev )
fi
rm /etc/portage/package.use/zzzzz_tmp.use
touch /etc/portage/package.use/zzzzz_tmp.use
#all but "github test systemd"
USE="abode accuweather acer_projector acmeda adguard ads aftership agent_dvr airly airvisual aladdin_connect alarmdecoder almond alpha_vantage ambiclimate ambient_station amcrest ampio analytics_insights android_ip_webcam androidtv androidtv_remote anthemav apache_kafka apcupsd apple_tv apprise aquostv arcam_fmj aruba asuswrt aten_pe atome august aurora_abb_powerone avea avion awair axis baidu backup beewi_smartclim bh1750 bitcoin bizkaibus blackbird blebox blink blinksticklight blinkt blockchain bluetooth bluetooth_le_tracker bluetooth_tracker bme280 bme680 bmw_connected_drive bond braviatv bring broadlink brottsplatskartan brunt bsblan bt_home_hub_5 bt_smarthub buienradar caldav camera canary cast cisco_mobility_express cli co2signal compensation coronavirus daikin deconz delijn denonavr deutsche_bahn devolo_home_control dexcom dhcp dht discogs discord discovery dlna_dmr dlna_dms doorbird dunehd dwd_weather_warnings dynalite dyson ecobee ecowitt emulated_roku enigma2 enocean enphase_envoy environment_canada esphome everlights evohome ffmpeg fibaro file flume flunearyou flux_led foobot forecast_solar fortios freebox fritz fritzbox fritzbox_callmonitor fronius garmin_connect gios glances gogogate2 greeneye_monitor growatt_server guardian harman_kardon_avr harmony heos here_travel_time holiday homematic homematicip_cloud homekit homekit_controller hp_ilo http hue hydrawise iaqualink ibeacon ihc image_upload imap incomfort influxdb insteon intesishome ipma ipp isal islamic_prayer_times jewish_calendar joaoapps_join kef knx kodi kraken lifx linode litterrobot local_calendar local_todo loopenergy luci luftdaten mariadb matter maxcube media_extractor met meteo_france mfi mikrotik mobile_app modbus mosquitto mqtt mysql nad nederlandse_spoorwegen netatmo netdata nextcloud nfandroidtv nmap_tracker notify_events nuki nut nws nx584 octoprint onkyo onvif opengarage opensensemap openweathermap opnsense otp owntracks panasonic_viera philips_js pi_hole pilight ping plex plugwise poolsense powerwall ps4 python_script qnap qvr_pro rachio radio_browser rainbird rainmachine recorder rejseplanen rest ring roku roomba roon samsungtv scrape season shelly shodan signal_messenger simplisafe skybell sma smappee smarthab smartthings snmp socat solax somfy sonos speedtestdotnet spotify sql squeezebox ssl statsd synology_dsm systemmonitor tankerkoenig tasmota tellduslive tesla tile tomorrowio toon totalconnect tplink tts tuya unifi unifi_direct upnp usb utility_meter vallox velbus velux vera version vicare vizio wake_on_lan waqi waze_travel_time webostv wemo whois wink withings wled workday xbox_live xiaomi_aqara xiaomi_miio xiaomi_tv xs1 yamaha yamaha_musiccast yeelight yi zeroconf zerproc zha zhong_hong zoneminder zwave_js" emerge --oneshot --autounmask --autounmask-write=y --autounmask-use=y --autounmask-backtrack=y --verbose-conflicts --backtrack=30 -va $pkg
dispatch-conf
USE="abode accuweather acer_projector acmeda adguard ads aftership agent_dvr airly airvisual aladdin_connect alarmdecoder almond alpha_vantage ambiclimate ambient_station amcrest ampio analytics_insights android_ip_webcam androidtv androidtv_remote anthemav apache_kafka apcupsd apple_tv apprise aquostv arcam_fmj aruba asuswrt aten_pe atome august aurora_abb_powerone avea avion awair axis baidu backup beewi_smartclim bh1750 bitcoin bizkaibus blackbird blebox blink blinksticklight blinkt blockchain bluetooth bluetooth_le_tracker bluetooth_tracker bme280 bme680 bmw_connected_drive bond braviatv bring broadlink brottsplatskartan brunt bsblan bt_home_hub_5 bt_smarthub buienradar caldav camera canary cast cisco_mobility_express cli co2signal compensation coronavirus daikin deconz delijn denonavr deutsche_bahn devolo_home_control dexcom dhcp dht discogs discord discovery dlna_dmr dlna_dms doorbird dunehd dwd_weather_warnings dynalite dyson ecobee ecowitt emulated_roku enigma2 enocean enphase_envoy environment_canada esphome everlights evohome ffmpeg fibaro file flume flunearyou flux_led foobot forecast_solar fortios freebox fritz fritzbox fritzbox_callmonitor fronius garmin_connect gios glances gogogate2 greeneye_monitor growatt_server guardian harman_kardon_avr harmony heos here_travel_time holiday homematic homematicip_cloud homekit homekit_controller hp_ilo http hue hydrawise iaqualink ibeacon ihc image_upload imap incomfort influxdb insteon intesishome ipma ipp isal islamic_prayer_times jewish_calendar joaoapps_join kef knx kodi kraken lifx linode litterrobot local_calendar local_todo loopenergy luci luftdaten mariadb matter maxcube media_extractor met meteo_france mfi mikrotik mobile_app modbus mosquitto mqtt mysql nad nederlandse_spoorwegen netatmo netdata nextcloud nfandroidtv nmap_tracker notify_events nuki nut nws nx584 octoprint onkyo onvif opengarage opensensemap openweathermap opnsense otp owntracks panasonic_viera philips_js pi_hole pilight ping plex plugwise poolsense powerwall ps4 python_script qnap qvr_pro rachio radio_browser rainbird rainmachine recorder rejseplanen rest ring roku roomba roon samsungtv scrape season shelly shodan signal_messenger simplisafe skybell sma smappee smarthab smartthings snmp socat solax somfy sonos speedtestdotnet spotify sql squeezebox ssl statsd synology_dsm systemmonitor tankerkoenig tasmota tellduslive tesla tile tomorrowio toon totalconnect tplink tts tuya unifi unifi_direct upnp usb utility_meter vallox velbus velux vera version vicare vizio wake_on_lan waqi waze_travel_time webostv wemo whois wink withings wled workday xbox_live xiaomi_aqara xiaomi_miio xiaomi_tv xs1 yamaha yamaha_musiccast yeelight yi zeroconf zerproc zha zhong_hong zoneminder zwave_js" emerge --oneshot --verbose-conflicts --backtrack=30 -va $pkg
rm /etc/portage/package.use/zzzzz_tmp.use
