name: function Search for update available upstream
on:
  workflow_call:
    inputs:
      upstream:
        description: 'Upstream URL'
        required: true
        type: string
      pkgName:
        description: 'Gentoo package'
        required: true
        type: string
      pkgCategory:
        description: 'Gentoo category'
        required: true
        type: string
jobs:
  check_upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Is last upstream version already known
      id: latest_version
      continue-on-error: true
      run: |
        latest_release=$( wget -qO - "https://api.github.com/repos/${{ inputs.upstream }}/releases/latest" | jq -r '.tag_name' )
        test ! -e "./${{ inputs.pkgCategory }}/${{ inputs.pkgName }}/${{ inputs.pkgName }}-${latest_release}.ebuild" && git switch -c "feature/${{ inputs.pkgName }}-${latest_release}" && git push --set-upstream origin feature/${{ inputs.pkgName }}-${latest_release}
