name: Check packages new releases
on:
  workflow_dispatch:  
  schedule:
    - cron: "2 3 * * 2-6" 
jobs:
  homeassistant:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/check-upstream.yml@master
    with:
      upstream: "home-assistant/core"
      pkgName: "homeassistant"
      pkgCategory: "app-misc"
    secrets: inherit
    
  zigbee2mqtt:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/check-upstream.yml@master
    with:
      upstream: "Koenkk/zigbee2mqtt"
      pkgName: "zigbee2mqtt"
      pkgCategory: "app-misc"
    secrets: inherit
    
  esphome:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/check-upstream.yml@master
    with:
      upstream: "esphome/esphome"
      pkgName: "esphome"
      pkgCategory: "dev-embedded"
    secrets: inherit
    
  homeassistant-cli:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/check-upstream.yml@master
    with:
      upstream: "home-assistant/home-assistant-cli"
      pkgName: "home-assistant-cli"
      pkgCategory: "app-misc"
    secrets: inherit
    
  node-red:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/check-upstream.yml@master
    with:
      upstream: "node-red/node-red"
      pkgName: "node-red"
      pkgCategory: "app-misc"
    secrets: inherit
