name: Continous Integration
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master
jobs:

  shellcheck_init:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: shellcheck
      pkg-version: 'shellcheck%20(running...)'
      pkg-status: 'failure'
      autoretry: true
    secrets: inherit
    
  shellcheck:
    name: shellcheck
    needs: shellcheck_init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -s bash -e SC2034 -e SC2016
      with:
        additional_files: '*.ebuild'
        
  shellcheck_complete:
    name: shellcheck_complete
    needs: [ shellcheck, pkgcheck_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: shellcheck
      pkg-version: shellcheck
      pkg-status: "success"
      autoretry: true
    secrets: inherit
    
  pkgcheck_init:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: shellcheck_init
    with:
      pkg-name: pkgcheck
      pkg-version: 'pkgcheck%20(running...)'
      pkg-status: 'failure'
      autoretry: true
    secrets: inherit
  
  pkgcheck:
    runs-on: ubuntu-latest
    needs: pkgcheck_init
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
      
  pkgcheck_complete:
    needs: [ pkgcheck, shellcheck_complete ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: pkgcheck
      pkg-version: pkgcheck
      pkg-status: "success"
      autoretry: true
    secrets: inherit

  esphome_init:
    if: github.event_name == 'pull_request'
    needs: [ pkgcheck_complete ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: esphomejob
      pkg-version: 'esphome%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  esphome_version:
    if: github.event_name == 'pull_request'
    needs: [ esphome_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'esphome'
      pkg-category: 'app-misc'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  esphome:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/esphome.yml@master
    needs: esphome_version
    secrets: inherit
    
  zigbee2mqtt_init:
    if: github.event_name == 'pull_request'
    needs: [ esphome_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: zigbee2mqttjob
      pkg-version: 'zigbee2mqtt%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit

  zigbee2mqtt_version:
    if: github.event_name == 'pull_request'
    needs: [ zigbee2mqtt_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'zigbee2mqtt'
      pkg-category: 'app-misc'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  zigbee2mqtt:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/zigbee2mqtt.yml@master
    needs: zigbee2mqtt_version
    secrets: inherit
    
  homeassistant_init_min:
    if: github.event_name == 'pull_request'
    needs: [ zigbee2mqtt_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'homeassistant_minimal'
      pkg-version: 'homeassistant[minimal]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init_normal:
    if: github.event_name == 'pull_request'
    needs: [ homeassistant_init_min ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'homeassistant_normal'
      pkg-version: 'homeassistant[normal]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init_full:
    if: github.event_name == 'pull_request'
    needs: [ homeassistant_init_normal ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'homeassistant_full'
      pkg-version: 'homeassistant[full]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: homeassistant_init_full
    with:
      pkg-name: 'homeassistant'
      pkg-category: 'app-misc'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/homeassistant.yml@master
    needs: homeassistant_init
    secrets: inherit
