name: Continous Integration
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - master
jobs:

  shellcheck_init:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: shellcheck
      pkg-version: 'shellcheck%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  shellcheck:
    name: shellcheck
    needs: shellcheck_init
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -s bash -e SC2034 -e SC2016
      with:
        additional_files: '*.ebuild'
        
  shellcheck_complete:
    if: success() || failure()
    name: shellcheck_complete
    needs: [ shellcheck, pkgcheck_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: shellcheck
      pkg-version: shellcheck
      pkg-status: ${{ jobs.shellcheck.result }}
      autoretry: true
    secrets: inherit
    
  pkgcheck_init:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: shellcheck_init
    with:
      pkg-name: pkgcheck
      pkg-version: 'pkgcheck%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
  
  pkgcheck:
    runs-on: ubuntu-latest
    needs: pkgcheck_init
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
      
  pkgcheck_complete:
    if: success() || failure()
    needs: [ pkgcheck, shellcheck_complete ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: pkgcheck
      pkg-version: pkgcheck
      pkg-status: ${{ jobs.pkgcheck.result }}
      autoretry: true
    secrets: inherit

  esphome_init:
    if: github.event_name == 'pull_request'
    needs: [ pkgcheck_complete ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: esphomejob
      pkg-version: 'esphome%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  esphome_version:
    if: github.event_name == 'pull_request'
    needs: [ esphome_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'esphome'
      pkg-category: 'dev-embedded'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  esphome:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/esphome.yml@master
    needs: esphome_version
    secrets: inherit
   
  zigbee2mqtt_init:
    if: github.event_name == 'pull_request'
    needs: [ esphome_version ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: zigbee2mqttjob
      pkg-version: 'zigbee2mqtt%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit

  zigbee2mqtt_version:
    if: github.event_name == 'pull_request'
    needs: [ zigbee2mqtt_init ]
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'zigbee2mqtt'
      pkg-category: 'app-misc'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  zigbee2mqtt:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/zigbee2mqtt.yml@master
    needs: zigbee2mqtt_version
    secrets: inherit

  homeassistant_init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        version=$( echo $( find ./app-misc/homeassistant -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git switch master
        git pull --no-rebase
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_minimal-\\)[^-]*-[^\\?]*/\\1homeassistant\\[minimal\\]%20\\(running\\.\\.\\.\\)-lightgrey/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_normal-\\)[^-]*-[^\\?]*/\\1homeassistant\\[normal\\]%20\\(running\\.\\.\\.\\)-lightgrey/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_full-\\)[^-]*-[^\\?]*/\\1homeassistant\\[full\\]%20\\(running\\.\\.\\.\\)-lightgrey/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant-\\)[^-]*-[^\\?]*/\\1${version}-lightgrey}/" README.md
        git add README.md
        git commit -m "CI homeassisant status" || true
        git pull --no-rebase
    
  homeassistant:
    if: github.event_name == 'pull_request'
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/homeassistant.yml@master
    needs: homeassistant_init
    secrets: inherit
