name: Gentoo build homeassistant

on:   
  workflow_dispatch:
  
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonfischl1980/gentoo-ci:main
      options: --privileged
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Init /etc/portage/      
      run: |
        rsync -aHDPSv etc/portage/ /etc/portage/
        
    - name: Setup HomeAssistant repository
      run: |
        mkdir -p /etc/portage/repos.conf/
        echo -en "[HomeAssistantRepository]\nlocation = " >/etc/portage/repos.conf/homeassistant.conf
        pwd -P >> /etc/portage/repos.conf/homeassistant.conf        

    - name: Setup portage to ~amd64 and python13
      run: |
        echo -e "ACCEPT_KEYWORDS=\"~amd64\"\nACCEPT_LICENCE=\"*\"" >> /etc/portage/make.conf
        echo -e "*/* PYTHON_TARGETS: -* python3_13\n*/* PYTHON_SINGLE_TARGET: -* python3_13" >> /etc/portage/package.use/python13.use
        echo "*/* *" >> /etc/portage/package.license
        
    - name: emerge-sync
      run: |
        sudo -u portage git -C /var/db/repos/gentoo pull
        emerge --sync -q
        
    - name : Move to python-13
      run: |
        emerge --jobs -q eix
        emerge --depclean -q dev-util/pkgcheck sys-apps/pkgcore app-eselect/eselect-repository
        eix-update
        USE="python_targets_python3_13 -python_targets_python3_12" emerge --oneshot `eix -I# --use python_targets_python3_12` --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 -q 
        
    - name: Free up some space
      run: |
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
                
    - name: Check that dependencies for homeassistant[full] are all there !
      run: |
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="-minimal -normal full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -vp || true
        
    - name: emerge homeassistant[minimal] first...
      run: |
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="minimal -normal -full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do cat $log; done
        USE="minimal -normal -full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Free up some space
      run: |
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
        
    - name: emerge then homeassistant[normal]
      run: |
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="-minimal normal -full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do cat $log; done
        USE="-minimal normal -full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Free up some space
      run: |
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
                
    - name: Finally try an emerge homeassistant[full] !
      run: |
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="-minimal -normal full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do cat $log; done
        USE="-minimal -normal full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Free up space
      run: |
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
