name: Docker Image CI

on:   
  workflow_dispatch:
  
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonfischl1980/gentoo-ci:main
      options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: emerge-sync
      run: |
        sudo -u portage git -C /var/db/repos/gentoo pull
        emerge --sync

    - name: Init /etc/portage/
      run: |
        rsync -aHDPSv etc/portage/ /etc/portage/

    - name: Fix Home Assistant repo
      run: |
        mkdir -p /etc/portage/repos.conf/
        echo -en "[HomeAssistantRepository]\nlocation = " >/etc/portage/repos.conf/HomeAssistantRepository.conf
        pwd -P >> /etc/portage/repos.conf/HomeAssistantRepository.conf
        cat /etc/portage/repos.conf/*.conf

    - name: emerge
      run: |
        emerge --info
    
