name: Docker Image CI

on:   
  workflow_dispatch:
  
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonfischl1980/gentoo-ci:main
      options: --privileged
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Init /etc/portage/
      run: |
        rsync -aHDPSv etc/portage/ /etc/portage/

    - name: Setup HomeAssistant repository
      run: |
        mkdir -p /etc/portage/repos.conf/
        echo -en "[HomeAssistantRepository]\nlocation = " >/etc/portage/repos.conf/homeassistant.conf
        pwd -P >> /etc/portage/repos.conf/homeassistant.conf

    - name: Setup portage to ~amd64 and python13
      run: |
        sed -i "s/ACCEPT_KEYWORDS="amd64"/ACCEPT_KEYWORDS=\"~amd64\"/g" /etc/portage/make.conf
        echo -e "*/* PYTHON_TARGETS: -* python3_13\n*/* PYTHON_SINGLE_TARGET: -* python3_13" >> /etc/portage/package.use/python13.use
        
    - name: emerge-sync
      run: |
        sudo -u portage git -C /var/db/repos/gentoo pull
        emerge --sync -q
        ls -l /etc/portage/
        emerge --jobs=16 -Dnuq --autounmask=y --autounmask-continue=y eselect 
        eselect profile list        
        
    - name: emerge update to python 13
      run: |
        emerge --jobs=16 -Dnuq --autounmask=y --autounmask-continue=y world
        
    - name: emerge homeassistant full :)
      run: |
        USE=full emerge --jobs=16 --autounmask=y --autounmask-continue=y -pv virtual/homeassistant
    
