name: esphome successfull
on:
  workflow_dispatch:
    inputs:
      status:
        type: choice
        description: Force action status
        options: 
        - success
        - failure
  workflow_run:
    workflows: ['esphome']
    types: completed
    branches: [master]
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update README.md
      run: |
        stat_success=238636
        stat_failure=f85149
        stat_=lightgrey
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/esphome-\\)[^-]*-[^\\?]*/\\1$( echo $( find ./dev-embedded/esphome -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )-${stat_${{ github.event.workflow_run.conclusion }}${{ github.event.inputs.status }}}/" README.md
    - name: GIT Commit
      run: |
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git add README.md
        git commit -m "Release esphome" || true
    
    - name: GIT Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
  
