name: esphome completed
on:
  workflow_dispatch:
    inputs:
      status:
        type: choice
        description: Force action status
        options: 
        - success
        - failure
  workflow_run:
    workflows: ['esphome']
    types: completed
    branches: [master]
jobs:
  job_status:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: esphomejob
      pkg-version: esphome
      pkg-status: ${{ github.event.workflow_run.conclusion }}
      autoretry: true
    secrets: inherit
  package_version:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: esphome
      pkg-category: dev-embedded
      pkg-status: ${{ github.event.workflow_run.conclusion }}
      autoretry: true
    secrets: inherit
