name: homeassistant

on:   
  workflow_dispatch:  
  pull_request:
    branches: [ "master" ]

jobs:
  homeassistant_init_min:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: 'homeassistant_minimal'
      pkg-version: 'homeassistant[minimal]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init_normal:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: homeassistant_init_min
    with:
      pkg-name: 'homeassistant_normal'
      pkg-version: 'homeassistant[normal]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init_full:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: homeassistant_init_normal
    with:
      pkg-name: 'homeassistant_full'
      pkg-version: 'homeassistant[full]%20(running...)'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_init:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    needs: homeassistant_init_full
    with:
      pkg-name: 'homeassistant'
      pkg-category: 'app-misc'
      pkg-status: ''
      autoretry: true
    secrets: inherit
    
  homeassistant_merge:
    # This job updates README.md with its protection, to avoid git conflict, we have to lock other script updating README.md
    concurrency: would_update_readme
    runs-on: ubuntu-latest
    needs: homeassistant_init
    container:
      image: ghcr.io/antonfischl1980/gentoo-ci:main
      options: --privileged
    steps:
    # synchronys my own git
    - name: Checkout code
      uses: actions/checkout@v4
    # 
    - name: Init /etc/portage/      
      run: |
        rsync -aHDPSv etc/portage/ /etc/portage/
        
    - name: Setup HomeAssistant repository
      run: |
        mkdir -p /etc/portage/repos.conf/
        echo -en "[HomeAssistantRepository]\nlocation = " >/etc/portage/repos.conf/homeassistant.conf
        pwd -P >> /etc/portage/repos.conf/homeassistant.conf        

    - name: Setup portage to ~amd64 and python13
      run: |
        echo -e "ACCEPT_KEYWORDS=\"~amd64\"\nACCEPT_LICENCE=\"*\"" >> /etc/portage/make.conf
        echo -e "*/* PYTHON_TARGETS: -* python3_13\n*/* PYTHON_SINGLE_TARGET: -* python3_13" >> /etc/portage/package.use/python13.use
        echo "*/* *" >> /etc/portage/package.license
        pwd
        git config --global --add safe.directory .
        git status
        
    - name: emerge homeassistant[minimal] first...
      id: merge_min
      run: |
        rm /etc/portage/package.use/._cfg0000_zzz.use || true
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="minimal -normal -full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do echo -e "$log\n======"; cat $log; done
        for log in $( find /etc/portage/ -type f ); do echo -e "$log\n======"; cat $log; done
        USE="minimal -normal -full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Update README, and cleanup up some space
      if: success() || failure()
      run: |
        stat_success=238636
        stat_failure=f85149
        stat_cancelled=lightgrey
        stat_skipped=lightgrey
        stat_=lightgrey
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git switch master
        git pull
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant-\\)[^-]*-[^\\?]*/\\1$( echo $( find ./app-misc/homeassistant -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )-${stat_${{ steps.merge_min.conclusion }}}/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_minimal-\\)[^-]*-[^\\?]*/\\1homeassistant[minimal]-${stat_${{ steps.merge_min.conclusion }}}/" README.md
        git add README.md
        git commit -m "Release homeassistant" || true
        git push --force-with-lease
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true

    # Last build normal features
    - name: emerge then homeassistant[normal]
      id: merge_normal
      run: |
        rm /etc/portage/package.use/._cfg0000_zzz.use || true
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="-minimal normal -full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do echo -e "$log\n======"; cat $log; done
        for log in $( find /etc/portage/ -type f ); do echo -e "$log\n======"; cat $log; done
        USE="-minimal normal -full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Free up some space
      if:  success() || failure()
      run: |
        stat_success=238636
        stat_failure=f85149
        stat_cancelled=lightgrey
        stat_skipped=lightgrey
        stat_=lightgrey
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git switch master
        git pull
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant-\\)[^-]*-[^\\?]*/\\1$( echo $( find ./app-misc/homeassistant -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )-${stat_${{ steps.merge_normal.conclusion }}}/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_normal-\\)[^-]*-[^\\?]*/\\1homeassistant[normal]-${stat_${{ steps.merge_normal.conclusion }}}/" README.md
        git add README.md
        git commit -m "Release homeassistant" || true
        git push --force-with-lease
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
    
    # Last build full features
    - name: Finally try an emerge homeassistant[full] !
      id: merge_full
      run: |
        rm /etc/portage/package.use/._cfg0000_zzz.use || true
        echo -n "" > /etc/portage/package.use/zzz.use
        USE="-minimal -normal full" emerge --jobs --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -q || true
        for log in $( find /var/tmp/portage/ | grep build.log ); do echo -e "\n$log\n======"; cat $log; done
        for log in $( find /etc/portage/ -type f ); do echo -e "\n$log\n======"; cat $log; done
        USE="-minimal -normal full" emerge --jobs=1 --autounmask=y --autounmask-continue=y --autounmask-write=y --autounmask-license=y --autounmask-backtrack=y --verbose-conflicts --backtrack=100 virtual/homeassistant -v
        
    - name: Free up space
      if: success() || failure()
      run: |
        stat_success=238636
        stat_failure=f85149
        stat_cancelled=lightgrey
        stat_skipped=lightgrey
        stat_=lightgrey
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git switch master
        git pull
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant-\\)[^-]*-[^\\?]*/\\1$( echo $( find ./app-misc/homeassistant -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )-${stat_${{ steps.merge_full.conclusion }}}/" README.md
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/homeassistant_full-\\)[^-]*-[^\\?]*/\\1homeassistant[full]-${stat_${{ steps.merge_full.conclusion }}}/" README.md
        git add README.md
        git commit -m "Release homeassistant" || true
        git push --force-with-lease
        rm /var/cache/distfiles/* || true 
        rm /var/cache/binpkgs/* || true 
        rm -rf /var/tmp/portage/* || true
