name: test

on:
  workflow_dispatch:
    inputs:
      status:
        type: choice
        description: Workflow status
        options: 
        - success
        - failure
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: |      
        stat_success=238636
        stat_failure=d43442
        stat_=lightgrey
        echo ${stat_${{ github.event.inputs.status }}}
