name: Update README.md file
on: 
  workflow_call:
    inputs:
      pkg-name: 
        description: 'Gentoo package name (ex: homeassistant)'
        required: true
        type: string
      pkg-category:
        description: 'Gentoo category (ex: app-misc)'
        type: string
      pkg-version:
        description: Force a version
        type: string
      pkg-status:
        description: 'Workflow status (success, failure)'
        type: string
      autoretry:
        default: true
        type: boolean
jobs:  
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update README.md
      run: |
        fix_readme() {
          sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/${{ inputs.pkg-name }}-\\)[^-]*-[^\\?]*/\\1${version}-${stat_${{ inputs.pkg-status }}}/" README.md
          git add README.md
          git commit -m "Release ${{ inputs.pkg-name }}" || true
          git pull
        }
        stat_success=238636
        stat_failure=f85149
        stat_=lightgrey
        version="${{ inputs.pkg-version }}"
        if [ -z "${version}" ] ; then
          version=$( echo $( find ./${{ inputs.pkg-category }}/${{ inputs.pkg-name }} -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )
        fi
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git pull
        fix_readme
        git push --force-with-lease || ( git restore README.md -s origin/master && fix_readme && git push --force-with-lease )
