name: Update README.md file
on: 
  workflow_call:
    inputs:
      pkg-name: 
        description: 'Gentoo package name (ex: homeassistant)'
        required: true
        type: string
      pkg-category:
        description: 'Gentoo category (ex: app-misc)'
        type: string
      pkg-version:
        description: Force a version
        type: string
      pkg-status:
        description: 'Workflow status (success, failure)'
        type: string
      pkg-noretry:
        type: boolean
jobs:  
  update_readme:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Update README.md
      run: |
        stat_success=238636
        stat_failure=f85149
        stat_=lightgrey
        version="${{ inputs.pkg-version }}"
        if [ -z "${version}" ] ; then
          version=$( echo $( find ./${{ inputs.pkg-category }}/${{ inputs.pkg-name }} -type f -name "*.ebuild" | sort -r | head -n1 ) | rev | cut -d/ -f1 | cut -d. -f2- | cut -d- -f1 | rev )
        fi
        git config --local user.name "xavier.forestier"
        git config --local user.email "{ID}+{username}@users.noreply.github.com"
        git fetch
        git pull
        sed -ie "s/\\(https:\\/\\/img\\.shields\\.io\\/badge\\/${{ inputs.pkg-name }}-\\)[^-]*-[^\\?]*/\\1${version}-${stat_${{ inputs.pkg-status }}}/" README.md
        git add README.md
        git commit -m "Release esphome" || true
        git push --force-with-lease
        
  retry:
    needs: update_readme
    if: ${{ failure() && !inputs.pkg-noretry }}
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: ${{ inputs.pkg-name }}
      pkg-category: ${{ inputs.pkg-category }}
      pkg-version: ${{ inputs.pkg-version }}
      pkg-status: ${{ inputs.pkg-status }}
      pkg-noretry: true
    secrets: inherit
