name: zigbee2mqtt completed
on:
  workflow_dispatch:
    inputs:
      status:
        type: choice
        description: Force action status
        options: 
        - success
        - failure
  workflow_run:
    workflows: ['zigbee2mqtt']
    types: completed
    branches: [master]
jobs:
  update_readme:
    uses: xavierforestier/HomeAssistantRepository/.github/workflows/update-readme.yml@master
    with:
      pkg-name: zigbee2mqtt
      pkg-category: app-misc
      pkg-status: ${{ github.event.workflow_run.conclusion }}
    secrets: inherit
